xline-kv/Xline

- curp/src/client.rs
Skip keyconflict error on the first rpc as we always wait the second
wait-sync response.
> fix propose_indexed bug

- curp/src/server.rs
Remove cmd from speculative pool after cmd is synced.
Without deleting cmd from speculative pool, speculative pool
increases infinitely very fast. This will causes big calculation
for conflict check.
With this wordaroud, it is still possible that cmd is synced
before cmd is proposed so that speculative pool will have cmd
that is never deleted. Need a formal fix for this.
> Temp workaround to clear speculative pool 

- curp/src/gc.rs
- curp/src/lib.rs
- curp/src/server.rs
- curp/src/sync_manager.rs
The bug will happen in the following situation:
1. A client proposes a command to all servers.
2. The leader receives the command, sync to others, and committed the command.
3. When a follower has not yet received the proposal from the client, it notices that the command is committed and executes it. When the execution is over, it will need to remove the command from spec pool. However, since the follower has not yet received a proposal from the client, it will find no such command in the spec pool.
Suggested fix:
When a follower tries to remove a non-exist command from spec pool, it will register the command id in an internal buffer. When the proposal is finally received, it will directly remove the command. (The ready pool needs to gc after some time)
> [Curp] Fix concurrent bug

- .gitignore
- curp/src/channel/key_spmc.rs
- xline/tests/common/mod.rs
- xline/tests/kv_test.rs
l.wait() should only be called in non-async code. If it is called in async code, it will not hand the control flow back to tokio runtime like l.await and, therefore, block the tokio worker thread.
> [Curp] Fix blocking caused by event listener wait() and improve kv_test

- CONTRIBUTING.md
- README.md
- curp/build.rs
- curp/src/server/bg_tasks.rs
This pr aims to fix issue #115.  It added a build option `--experimental_allow_proto3_optional` to make the `cargo build --release` run successfully.
Signed-off-by: Phoeniix Zhao <Phoenix500526@163.com>
> fix proto compile error

- benchmark/src/runner.rs
- scripts/benchmark.sh
A panic happened in the first bench case when I run the `benchmark.sh`.  That's because the benchmark program sent requests to the cluster while it is not yet booted up.
> fix panic in a benchmark

- .github/workflows/coverage.yml
- .mergify.yml
The auto merge should be blocked when `Coverage` failed in the CI workflow.
No
> add Coverage check in .mergify.yml

- .github/workflows/validation.yml
- .gitignore
- .mergify.yml
- scripts/quick_start.sh
- scripts/validation_test.sh
- xline/src/bin/lock_client.rs
Execute etcd validation test automatically
Add a script to validate, and run this script in 
No
based on #153
> Validation

- xline/Cargo.toml
- xline/src/header_gen.rs
- xline/src/lib.rs
- xline/src/main.rs
- xline/src/revision_number.rs
- xline/src/server/watch_server.rs
- xline/src/server/xline_server.rs
- xline/src/storage/auth_store/backend.rs
- xline/src/storage/kv_store.rs
- xline/src/storage/kvwatcher.rs
- xline/src/storage/revision.rs
- xline/tests/common/mod.rs
1. Watcher should be an inner struct in the storage module. It should not appear in the server module. WatchServer only needs to maintain watch_id, no need to maintain watcher.
2. Some renaming
3. Use a RwLock to store watchers so that different watchers can send concurrently
4. Unnecessary Arc<Inner>: Watcher has an inner of type Arc<WatcherInner>. When Watcher needs to be shared, we previously Clone on Watcher. Just use Arc<Watcher> is both clearer and simpler.
5. Improve filter events performance: previously events are filtered by key_range twice, now only once
6. Watch id should be assigned from 1 instead of 0 because 0 means auto-generated, which might be confusing to the client
7. Reduce code duplication
8. Use atomici64 for the revision number.
9. Fix in auth backend concurrent …
> refactor and improve xline server

- utils/src/lib.rs
- xline/src/lib.rs
- xline/src/main.rs
- xline/src/rpc/mod.rs
- xline/src/server/auth_server.rs
- xline/src/server/command.rs
- xline/src/server/kv_server.rs
- xline/src/server/lease_server.rs
- xline/src/server/lock_server.rs
- xline/src/server/watch_server.rs
- xline/src/server/xline_server.rs
- xline/src/storage/auth_store/backend.rs
- xline/src/storage/auth_store/store.rs
- xline/src/storage/db.rs
- xline/src/storage/kv_store.rs
- xline/src/storage/kvwatcher.rs
- xline/src/storage/memory.rs
- xline/src/storage/mod.rs
- xline/src/storage/revision.rs
- xline/src/storage/storage_api.rs
- xline/tests/common/mod.rs
Abstract a storage layer to make persistent storage easier
Abstract the storage layer as a trait similar to `HashMap`, and use `Mutex<HashMap<Vec<u8>,Vet<u8>>>` to provide a default in-memory implementation
No
> abstract DB as a trait

- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/docker.yml
- .github/workflows/validation.yml
- curp/src/client.rs
- curp/src/lib.rs
- curp/src/server/bg_tasks.rs
- curp/src/server/cmd_worker.rs
- curp/src/server/mod.rs
- curp/tests/common/curp_group.rs
- rust-toolchain.toml
- utils/src/lib.rs
- utils/src/std_lock.rs
- xline/src/bin/lock_client.rs
- xline/src/client/mod.rs
- xline/src/id_gen.rs
- xline/src/lib.rs
- xline/src/server/auth_server.rs
- xline/src/server/kv_server.rs
- xline/src/server/lease_server.rs
- xline/src/server/lock_server.rs
- xline/src/server/watch_server.rs
- xline/src/storage/auth_store/backend.rs
- xline/src/storage/auth_store/perms.rs
- xline/src/storage/auth_store/store.rs
- xline/src/storage/db.rs
- xline/src/storage/index.rs
- xline/src/storage/kv_store.rs
- xline/src/storage/lease_store/mod.rs
Dependency error
bump rust toolchain to 1.67.1
> bump rust toolchain to 1.67.1 and fix clippy warnings

- USAGE.md
- curp/Cargo.toml
- curp/src/cmd.rs
- curp/src/server/curp_node.rs
- curp/src/server/mod.rs
- curp/src/server/raw_curp/log.rs
- curp/src/server/raw_curp/mod.rs
- curp/src/server/raw_curp/state.rs
- curp/src/server/raw_curp/tests.rs
- curp/src/server/storage/mod.rs
- curp/src/server/storage/rocksdb.rs
- curp/src/test_utils/mod.rs
- curp/src/test_utils/test_cmd.rs
- curp/tests/common/curp_group.rs
- curp/tests/common/mod.rs
- curp/tests/common/test_cmd.rs
- curp/tests/server_recovery.rs
- utils/src/config.rs
- xline/Cargo.toml
- xline/src/main.rs
- xline/src/server/command.rs
- xline/src/server/xline_server.rs
- xline/tests/common/mod.rs
- xline_server.conf
Based on #178 
Persist log entries and `voted_for`.
This PR also rename `ServerTimeout` config to `CurpConfig` since now it will contain data dir.
> [Curp] Log entry persistency

- engine/src/error.rs
- engine/src/rocksdb_engine.rs
refactor rocksdb engine implement
modify `EngineError::IoError` and refactor the rocksdb `From<RocksError>` trait.
No
> [refactor]: refactor engine error

- curp/src/client.rs
- curp/src/rpc/connect.rs
- curp/src/server/curp_node.rs
Use anonymous generic parameter instead of dynamic object of connect. Static generic is faster than static genericl
> Use anonymous generic parameter instead of dynamic object of connect

- curp/src/server/gc.rs
- curp/src/server/spec_pool.rs
Panic in gc
The cause of this bug: spec pool is also modified in cmd worker when a cmd finished after sync. So it's possible that the `last_checked_len` > `spec.len()`. So, instead of recording the length, we now record all keys in spec pool. Admittedly, the cloning of all keys in spec pool will take more time, but I think it's not a big issue since spec pool is usually small.
> Fix [Bug]: gc panic during a benchmark  #206

- curp/src/client.rs
- curp/src/cmd.rs
- curp/src/lib.rs
- curp/src/log_entry.rs
- curp/src/message.rs
- curp/src/rpc/connect.rs
- curp/src/rpc/mod.rs
- curp/src/server/cmd_worker/conflict_checked_mpmc.rs
- curp/src/server/cmd_worker/mod.rs
- curp/src/server/curp_node.rs
- curp/src/server/mod.rs
- curp/src/server/raw_curp/log.rs
- curp/src/server/raw_curp/mod.rs
- curp/src/server/raw_curp/state.rs
- curp/src/server/raw_curp/tests.rs
- curp/src/server/storage/mod.rs
- curp/src/server/storage/rocksdb.rs
- curp/src/test_utils/test_cmd.rs
- curp/tests/common/test_cmd.rs
Use `LogIndex`(u64) for log index. We previously use `usize` for log index. `usize` may have different size on different machines, which may result in unexpected bugs.
> Use LogIndex for log index

- curp/src/server/curp_node.rs
- curp/src/server/raw_curp/mod.rs
- curp/src/server/raw_curp/state.rs
- curp/src/server/raw_curp/tests.rs
- xline/tests/kv_test.rs
As described in #223, this PR unify all AE generation functions to one, which will generate ae according to next_index only. And now, one sync task corresponds to one follower now.
Based on #217.
> Unified AE entry

- .github/workflows/benchmark.yml
- benchmark/src/args.rs
- benchmark/src/runner.rs
- curp/src/server/cmd_worker/mod.rs
- curp/src/server/curp_node.rs
- curp/tests/common/curp_group.rs
- scripts/benchmark.sh
- scripts/quick_start.sh
- utils/src/config.rs
- xline/src/main.rs
We set 100ms to simulate the latency on the WAN, but our retry timeout and rpc timeout is only 50ms. Therefore,we need to extent the rpc timeout and retry timeout
> add some necessary config to boot up an xline cluster in benchmark

- curp/tests/common/curp_group.rs
- xline/tests/common/mod.rs
After running the test, many useless directories will be left under the tmp directory
clear curp tmp directory after test
no
> fix: clear curp tmp directory after test

- curp/Cargo.toml
- curp/proto/message.proto
- curp/src/cmd.rs
- curp/src/lib.rs
- curp/src/rpc/connect.rs
- curp/src/rpc/mod.rs
- curp/src/server/cmd_worker/conflict_checked_mpmc.rs
- curp/src/server/cmd_worker/mod.rs
- curp/src/server/curp_node.rs
- curp/src/server/mod.rs
- curp/src/server/raw_curp/log.rs
- curp/src/server/raw_curp/mod.rs
- curp/src/server/raw_curp/tests.rs
- curp/src/server/storage/mod.rs
- curp/src/server/storage/rocksdb.rs
- curp/src/snapshot.rs
- curp/src/test_utils/test_cmd.rs
- curp/tests/common/test_cmd.rs
- engine/src/engine_api.rs
- xline/src/server/command.rs
Implement snapshot of curp. Based on #224.
Note that without compaction, the snapshot will never be triggered. Compaction will be next PR. As a result, the test is lacking and will be added in next PR.
> Curp snapshot

- curp/proto/message.proto
- curp/src/client.rs
- curp/src/cmd.rs
- curp/src/rpc/connect.rs
- curp/src/rpc/mod.rs
- curp/src/server/cmd_worker/conflict_checked_mpmc.rs
- curp/src/server/cmd_worker/mod.rs
- curp/src/server/curp_node.rs
- curp/src/server/mod.rs
- curp/src/server/raw_curp/mod.rs
- curp/src/test_utils/test_cmd.rs
- curp/tests/common/test_cmd.rs
- curp/tests/read_state.rs
- engine/src/rocksdb_engine.rs
- utils/src/config.rs
- xline/src/main.rs
- xline/src/rpc/mod.rs
- xline/src/server/barriers.rs
- xline/src/server/command.rs
- xline/src/server/kv_server.rs
- xline/src/server/mod.rs
- xline/src/server/xline_server.rs
- xline/src/storage/db.rs
- xline/tests/common/mod.rs
fix wrong range processing
when follower receives range request, it will send fetch read state request to leader, leader will return a group of propose id or commit index, follower will wait these id or index applied, then it can safely read from its own state machine and return.
no
> refactor kv range request

- engine/src/rocksdb_engine.rs
- xline/src/bin/restore_client.rs
- xline/src/client/errors.rs
- xline/src/client/mod.rs
- xline/src/client/restore.rs
- xline/src/server/maintenance.rs
- xline/src/server/mod.rs
- xline/src/server/xline_server.rs
- xline/src/storage/db.rs
- xline/tests/common/mod.rs
- xline/tests/maintenance.rs
add recover logic of maintenance snapshot file
implement a tmp client to restore, will be merge in our own client in the future
no
> recover persistent storage from snapshot file

- curp/src/client.rs
- curp/src/rpc/connect.rs
- curp/src/server/curp_node.rs
- curp/src/server/raw_curp/mod.rs
- curp/src/server/raw_curp/tests.rs
- engine/src/memory_engine.rs
- engine/src/rocksdb_engine.rs
- engine/src/snapshot_api/rocks_snapshot.rs
- utils/src/config.rs
- xline/src/main.rs
- xline/src/storage/db.rs
use async_stream::stream! to generate install_snapshot stream, closes #230 
Viewing #230 for more details.
No
> Refactor: improve install_snapshot_stream generation logic

- xline/Cargo.toml
- xline/src/server/lease_server.rs
use async_stream::stream! to generate lease_keep_alive stream, closes #158 
Reading #158  for more details.
No
> refactor: improve lease server lease_keep_alive implementation

- curp/src/test_utils/test_cmd.rs
- curp/tests/common/curp_group.rs
- curp/tests/common/test_cmd.rs
- curp/tests/server_recovery.rs
Some pre-work for refactoring the engine, the next PR will use the engine to replace the store, and the engine cannot use u32 as a key
Use `Vec<u8>` as key and value instead of `u32` in Curp tests
no
> Use `Vec<u8>` as key and value instead of `u32` in tests

- curp/src/lib.rs
- curp/src/rpc/connect.rs
- curp/src/server/cmd_worker/conflict_checked_mpmc.rs
- curp/src/server/cmd_worker/mod.rs
- curp/src/server/curp_node.rs
- curp/src/server/mod.rs
- curp/src/server/raw_curp/log.rs
- curp/src/server/raw_curp/mod.rs
- curp/src/server/storage/mod.rs
- curp/src/server/storage/rocksdb.rs
- curp/src/snapshot.rs
- curp/src/test_utils/test_cmd.rs
- curp/tests/common/curp_group.rs
- curp/tests/common/test_cmd.rs
- curp/tests/server_recovery.rs
- engine/src/engine_api.rs
- engine/src/memory_engine.rs
- engine/src/rocksdb_engine.rs
- engine/src/snapshot_api/rocks_snapshot.rs
- utils/src/config.rs
- xline/src/client/restore.rs
- xline/src/main.rs
- xline/src/server/command.rs
- xline/src/server/xline_server.rs
- xline/src/storage/db.rs
- xline/src/storage/mod.rs
- xline/src/storage/snapshot_allocator.rs
- xline/src/storage/storage_api.rs
- xline/tests/common/mod.rs
Based on #186, #217 
This PR adds log compaction for curp. I.e., we will only reserve a certain number of logs in memory. And if a follower requests for logs that have been compacted, the leader will take a snapshot and send it to the follower.
P.S. I've added a `SnapshotAllocator` API for Xline to implement. Current implementation is insufficient and not tested.
P.S.2 I've renamed our `last_applied` to `last_as` and added a new field `last_exe` because of our two-stage cmd process that is different from the one in original raft. `last_exe` helps us to generate the correct snapshot meta.
* are there …
> Curp log compaction

- curp/src/server/raw_curp/mod.rs
fix https://github.com/datenlord/Xline/issues/280
One line change in `handle_propose`, compare follower index with leader base_index.
> fix potential panic in `handle_propose`

- .github/workflows/ci.yml
Close issue #304.
Read issue #304 for more detail.
> ci: skip commit message check job when executing scheduled ci on master branch

- engine/Cargo.toml
see https://github.com/facebook/rocksdb/pull/11118
rust-rocksdb v0.21.0 have included this commit
> fix: fix build with gcc 13 by bumping rust-rocksdb to v0.21.0

- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/docker.yml
- .github/workflows/release.yml
- .github/workflows/validation.yml
- CONTRIBUTING.md
- benchmark/src/lib.rs
- benchmark/src/runner.rs
- curp-external-api/src/lib.rs
- curp/src/lib.rs
- curp/src/server/cmd_board.rs
- engine/src/lib.rs
- rust-toolchain.toml
- utils/src/lib.rs
- xline-client/src/lib.rs
- xline/src/client/restore.rs
- xline/src/lib.rs
- xline/src/main.rs
- xline/src/server/command.rs
- xline/src/storage/index.rs
- xline/src/storage/kvwatcher.rs
- xlineapi/src/lib.rs
Described in #336 
Bump Rust toolchain to 1.70.0
> Chore/Bump Rust toolchain to 1.70.0

- .pre-commit-config.yaml
add commit message hook to validate commit messages locally
> chore: add commit-msg hook to validate commit message

- .github/scripts/Dockerfile.aarch64-unknown-linux-gnu
- .github/scripts/Dockerfile.x86_64-unknown-linux-gnu
- .github/scripts/install_macos_deps.sh
- .github/workflows/docker.yml
- .github/workflows/merge_image.yml
- .github/workflows/release.yml
- Cross.toml
- doc/quick-start/README.md
The test workflow: https://github.com/iGxnon/rust-ci-test/actions/runs/5362996116
Etcd images are compatible with computers that have ARM architecture. Additionally, xline can also support ARM thanks to Rust's cross-compilation.
This pull request updated the release's CI to allow for automatic building of ARM images.
- Added ARM image building process in Github Action CI
- Added release artifacts for macOS and ARM Linux
- Reorganize quick-start readme
No
> Feature/Release ARM Image

- test-macros/src/lib.rs
> test: add test case information in abort_on_panic macros

- simulation/src/curp_group.rs
- simulation/tests/it/curp/server_election.rs
- simulation/tests/it/curp/server_recovery.rs
Described in : #361
1. change `all_crash_and_recovery` to `minority_crash_and_recovery`. This test does not match the assumption of current implementation(that the majority of nodes should not crash), therefore lead to a test failure.
2. refactor some assumptions based on time synchronization, makes these test runs more stable under madsim simulated time.
> fix: resolve failing madsim tests

- curp-test-utils/src/test_cmd.rs
- curp/src/server/raw_curp/mod.rs
- curp/src/server/raw_curp/tests.rs
- simulation/tests/it/curp/server_recovery.rs
> fix: remove the reapplication of log entries when leader retires

- xlinectl/src/command/get.rs
- xlinectl/src/command/put.rs
- xlinectl/src/main.rs
- xlinectl/src/utils/printer.rs
add more printer format option for xlinectl
add a new `Printer` trait, and implement it for each response type.
> refactor: xlinectl printer

- xline-client/examples/kv.rs
- xline-client/src/clients/kv.rs
- xline-client/src/types/kv.rs
- xline-client/tests/kv.rs
based on: #311
The compact method in `xline-client` can be implement after #311
> feat: implement client compact

- xline-client/examples/kv.rs
- xline-client/src/clients/auth.rs
- xline-client/src/clients/kv.rs
- xline-client/src/clients/lease.rs
- xline-client/src/clients/maintenance.rs
- xline-client/src/clients/watch.rs
- xline-client/src/lib.rs
- xline-client/src/types/auth.rs
- xline-client/src/types/kv.rs
- xline-client/src/types/lease.rs
- xline-client/src/types/watch.rs
- xline-client/tests/auth.rs
- xline-client/tests/kv.rs
- xline-client/tests/watch.rs
This PR is based on #372
descibed in `Update documents` section in #369
Add more detailed descriptions to some methods and types.
> doc: update xline client document

- curp-external-api/src/cmd.rs
- curp-test-utils/src/test_cmd.rs
- curp/src/client.rs
- curp/src/error.rs
- curp/src/rpc/connect.rs
- curp/src/rpc/mod.rs
- curp/src/server/cmd_board.rs
- curp/src/server/cmd_worker/conflict_checked_mpmc.rs
- curp/src/server/cmd_worker/mod.rs
- curp/src/server/curp_node.rs
- simulation/src/curp_group.rs
- xline-client/src/error.rs
- xline/src/client/errors.rs
- xline/src/server/auth_server.rs
- xline/src/server/command.rs
- xline/src/server/common.rs
- xline/src/server/kv_server.rs
- xline/src/server/lease_server.rs
- xline/src/server/lock_server.rs
- xline/src/server/mod.rs
- xline/src/storage/auth_store/backend.rs
- xline/src/storage/auth_store/store.rs
- xline/src/storage/execute_error.rs
- xline/src/storage/kv_store.rs
- xline/src/storage/lease_store/lease_collection.rs
- xline/src/storage/lease_store/mod.rs
- xline/src/storage/mod.rs
> refactor: execution error types

- xline-client/README.md
- xline-client/examples/auth.rs
- xline-client/examples/auth_role.rs
- xline-client/examples/auth_user.rs
- xline-client/examples/error_handling.rs
- xline-client/examples/kv.rs
- xline-client/examples/lease.rs
- xline-client/examples/lock.rs
- xline-client/examples/maintenance.rs
- xline-client/examples/watch.rs
- xline-client/src/clients/auth.rs
- xline-client/src/clients/kv.rs
- xline-client/src/clients/lease.rs
- xline-client/src/clients/lock.rs
- xline-client/src/clients/maintenance.rs
- xline-client/src/clients/watch.rs
- xline-client/src/lib.rs
This PR is based on #373 
descibed in `Add examples to the crate` section in #369 
Add use examples to xline client
> doc: add examples to xline client

- xline-client/tests/kv.rs
- xline/src/lib.rs
- xline/src/request_validation.rs
- xline/src/revision_check.rs
- xline/src/server/auth_server.rs
- xline/src/server/kv_server.rs
- xline/src/storage/auth_store/store.rs
- xline/src/storage/execute_error.rs
- xline/src/storage/kv_store.rs
Described in: #398
Based on: #399
Currently some of the validation checks are done in the RPC server. However, these checks are not applied in the storage request handlers (eg. `handle_range_request`), so that the request from outside client will not be checked.
This pull request applied the validation check in both RPC server and the storage handlers.
> refactor: request validation check

- curp/proto/message.proto
- curp/src/client.rs
- curp/src/error.rs
- curp/src/lib.rs
- curp/src/members.rs
- curp/src/rpc/connect.rs
- curp/src/rpc/mod.rs
- curp/src/server/cmd_worker/mod.rs
- curp/src/server/curp_node.rs
- curp/src/server/mod.rs
- curp/src/server/raw_curp/mod.rs
- curp/src/server/raw_curp/state.rs
- curp/src/server/raw_curp/tests.rs
- curp/src/server/storage/db.rs
- curp/src/server/storage/mod.rs
- curp/tests/common/curp_group.rs
- curp/tests/server.rs
- simulation/src/curp_group.rs
- simulation/tests/it/curp/server_election.rs
- simulation/tests/it/curp/server_recovery.rs
- xline-test-utils/src/lib.rs
- xline/src/header_gen.rs
- xline/src/id_gen.rs
- xline/src/main.rs
- xline/src/server/lease_server.rs
- xline/src/server/xline_server.rs
#306 
Based on #412 
If we use `String` as the server ID, it is not compatible with the `etcd`'s membership change interface, and using String as the server ID will require clone in many cases, So we need to turn server ID into u64.
use u64 as ServerId instead of String, and  refactor check vote logic
yes, All server ID related parts need to be replaced with `u64`
> refactor: use u64 as ServerId

- clippy.toml
Described in `clippy.toml`
As the title said
No
> chore: disallow use of EventListener::wait

- utils/src/lib.rs
- xline/src/main.rs
#330 
When the configuration file doesn't exist, Xline will throw out an error message, "Error: No such file or directory (os error 2)", which lacks readability. We need to improve its readability by adding the configuration file name in this error message.
Add error messages when reading of the config file fails.
> fix: improve readability of bootstrap errors

- .github/scripts/install_deps.sh
- curp-external-api/src/cmd.rs
- curp-test-utils/src/test_cmd.rs
- curp/build.rs
- curp/proto/command.proto
- curp/proto/error.proto
- curp/proto/message.proto
- curp/src/client.rs
- curp/src/error.rs
- curp/src/lib.rs
- curp/src/rpc/connect.rs
- curp/src/rpc/mod.rs
- curp/src/server/curp_node.rs
- curp/src/server/gc.rs
- curp/tests/common/curp_group.rs
- curp/tests/server.rs
- simulation/tests/it/curp/server_recovery.rs
- xline/src/server/command.rs
- xline/src/storage/execute_error.rs
- xlineapi/proto/command.proto
- xlineapi/proto/error.proto
- xlineapi/src/lib.rs
Described in: #420 
Based on: #421 
> refactor: command after sync serialization 

- curp/proto/message.proto
- curp/src/error.rs
- curp/src/members.rs
- curp/src/rpc/mod.rs
- curp/src/server/cmd_worker/mod.rs
- curp/src/server/curp_node.rs
- curp/src/server/mod.rs
- curp/src/server/raw_curp/mod.rs
- curp/src/server/raw_curp/state.rs
- curp/src/server/raw_curp/tests.rs
- curp/tests/common/curp_group.rs
- simulation/src/curp_group.rs
- xline/src/server/lease_server.rs
- xline/src/server/xline_server.rs
#306 
apply config change to curp
refactor data structures via `DashMap`, and modify them when apply_conf_change
no
> feature: add `apply_conf_change` method for `RawCurp`

- xline/src/server/auth_server.rs
- xline/src/server/lease_server.rs
- xline/src/server/xline_server.rs
- xline/src/storage/auth_store/store.rs
`AuthServer::authenticate` should not check password locally.
Move the `check_password` to the leader.
No
> fix: check the password on leader

- xlinectl/README.md
- xlinectl/src/command/auth/disable.rs
- xlinectl/src/command/auth/enable.rs
- xlinectl/src/command/auth/mod.rs
- xlinectl/src/command/auth/status.rs
- xlinectl/src/command/mod.rs
- xlinectl/src/command/snapshot.rs
- xlinectl/src/main.rs
- xlinectl/src/utils/printer.rs
> feat: implement xlinectl `snapshot` and `auth` commands

- curp/src/server/raw_curp/mod.rs
- curp/src/server/raw_curp/tests.rs
- simulation/src/curp_group.rs
- simulation/tests/it/curp/server_election.rs
> fix: execute out of order

- simulation/tests/it/curp/server_election.rs
> fix: remove `stop` in simulation tests

- benchmark/src/runner.rs
- xline/src/server/auth_server.rs
- xline/src/storage/compact/mod.rs
> fix: benchmark client cannot connect to server

- curp/src/client.rs
- curp/src/error.rs
- curp/src/log_entry.rs
- curp/src/rpc/mod.rs
- curp/src/server/cmd_worker/conflict_checked_mpmc.rs
- curp/src/server/cmd_worker/mod.rs
- curp/src/server/curp_node.rs
- curp/src/server/raw_curp/log.rs
- curp/src/server/raw_curp/mod.rs
- curp/src/server/raw_curp/tests.rs
- curp/tests/server.rs
In the current implementation, all log entries require propose id, but some log, such as shutdown and no-op log that will be introduced in the future, do not need propose id.
use Logindex instead of ProposeId in cmd_vid, after this refactor, now the log entry no longer has to include ProposeId
no
> refactor: use `Logindex` instead of `ProposeId` in `cmd_vid`

- Cargo.lock
- curp-external-api/Cargo.toml
- curp-external-api/src/cmd.rs
- curp-test-utils/src/test_cmd.rs
- curp/Cargo.toml
- curp/src/client.rs
- curp/tests/common/curp_group.rs
- xline-client/src/clients/auth.rs
- xline-client/src/clients/kv.rs
- xline-client/src/clients/lease.rs
- xline-client/src/clients/lock.rs
- xline-client/src/lib.rs
- xline/src/client/mod.rs
- xline/src/server/auth_server.rs
- xline/src/server/kv_server.rs
- xline/src/server/lease_server.rs
- xline/src/server/lock_server.rs
- xline/src/server/xline_server.rs
- xline/src/storage/compact/mod.rs
- xline/src/storage/compact/periodic_compactor.rs
- xline/src/storage/compact/revision_compactor.rs
This PR refactors ProposeId into `<client_id>#<seq_num>`, The client_id will be generated by the lease manager(not implemented in this PR), and the seq_num will ensure that all IDs are unique and ordered under the same client_id.
As above
No
> refactor: refactor propose id into `<client_id>#<seq_num>`

- curp/build.rs
- curp/src/client.rs
- curp/src/error.rs
- curp/src/log_entry.rs
- curp/src/members.rs
- curp/src/rpc/connect.rs
- curp/src/rpc/mod.rs
- curp/src/server/cmd_board.rs
- curp/src/server/cmd_worker/conflict_checked_mpmc.rs
- curp/src/server/cmd_worker/mod.rs
- curp/src/server/curp_node.rs
- curp/src/server/gc.rs
- curp/src/server/mod.rs
- curp/src/server/raw_curp/log.rs
- curp/src/server/raw_curp/mod.rs
- curp/src/server/raw_curp/state.rs
- curp/src/server/raw_curp/tests.rs
- curp/src/server/spec_pool.rs
- curp/src/server/storage/db.rs
- curp/tests/common/curp_group.rs
- curp/tests/server.rs
- simulation/src/curp_group.rs
- simulation/tests/it/curp/server_recovery.rs
- xline/src/server/xline_server.rs
described in  #306 
based on #433 ,https://github.com/xline-kv/curp-proto/pull/10
propose config change
implement `propose_conf_change` rpc
no
> Propose conf change

- curp-test-utils/src/test_cmd.rs
- curp/src/members.rs
- curp/src/rpc/mod.rs
- curp/src/server/curp_node.rs
- curp/src/server/raw_curp/mod.rs
- curp/src/server/raw_curp/state.rs
- curp/src/server/raw_curp/tests.rs
- simulation/src/curp_group.rs
> Add learner

- xline-client/src/types/kv.rs
- xline-client/src/types/lock.rs
- xline-client/src/types/maintenance.rs
- xline-client/src/types/mod.rs
We don't need to import the xlineapi crate separately when using the xline client.
> chore: re-export response type in client

- curp/src/client.rs
- curp/src/server/curp_node.rs
- curp/src/server/raw_curp/mod.rs
- curp/tests/common/curp_group.rs
- curp/tests/read_state.rs
- simulation/src/curp_group.rs
- xline-test-utils/src/bin/validation_lock_client.rs
- xline/src/server/cluster_server.rs
- xline/src/server/maintenance.rs
- xline/tests/lock_test.rs
proto changes: https://github.com/xline-kv/curp-proto/pull/14
Fix linearizable read in FetchClusterRequest
> fix: add linearizable parameter in FetchClusterRequest

- Cargo.lock
- xline-client/src/types/cluster.rs
- xline-client/src/types/kv.rs
- xlinectl/Cargo.toml
- xlinectl/README.md
- xlinectl/src/command/compaction.rs
- xlinectl/src/command/member/add.rs
- xlinectl/src/command/member/list.rs
- xlinectl/src/command/member/mod.rs
- xlinectl/src/command/member/promote.rs
- xlinectl/src/command/member/remove.rs
- xlinectl/src/command/member/update.rs
- xlinectl/src/command/mod.rs
- xlinectl/src/main.rs
- xlinectl/src/utils/printer.rs
> feat: implement xlinectl compaction and member commands 

- curp-external-api/src/cmd.rs
- curp-test-utils/src/test_cmd.rs
- curp/build.rs
- curp/src/client.rs
- curp/src/log_entry.rs
- curp/src/rpc/connect.rs
- curp/src/rpc/mod.rs
- curp/src/server/cmd_board.rs
- curp/src/server/cmd_worker/mod.rs
- curp/src/server/curp_node.rs
- curp/src/server/gc.rs
- curp/src/server/mod.rs
- curp/src/server/raw_curp/log.rs
- curp/src/server/raw_curp/mod.rs
- curp/src/server/raw_curp/tests.rs
- curp/src/server/spec_pool.rs
- curp/tests/common/curp_group.rs
- curp/tests/read_state.rs
- xline/src/server/barriers.rs
- xline/src/server/cluster_server.rs
- xline/src/server/command.rs
- xlineapi/src/lib.rs
proto changes: https://github.com/xline-kv/curp-proto/pull/15 https://github.com/xline-kv/xline-proto/pull/5
Refactor propose id into `ProposeId(u64, u64)`
> refactor: refactor propose id

- curp/src/client.rs
- curp/src/error.rs
- curp/src/log_entry.rs
- curp/src/members.rs
- curp/src/rpc/mod.rs
- curp/src/server/cmd_worker/conflict_checked_mpmc.rs
- curp/src/server/cmd_worker/mod.rs
- curp/src/server/curp_node.rs
- curp/src/server/raw_curp/mod.rs
- curp/src/server/raw_curp/tests.rs
- curp/tests/common/curp_group.rs
- curp/tests/server.rs
- simulation/src/curp_group.rs
- simulation/tests/it/curp/server_recovery.rs
- xline-client/src/error.rs
- xline/src/server/cluster_server.rs
described in #306 
based on #449 
> Client discover cluster

- Cargo.lock
- benchmark/Cargo.toml
- benchmark/src/bench_client.rs
slove #486 
refactored the internal implementation of the beanch client."
no
> refactor: bench client

- curp/src/client.rs
- curp/src/log_entry.rs
- curp/src/members.rs
- curp/src/rpc/connect.rs
- curp/src/rpc/mod.rs
- curp/src/server/cmd_worker/conflict_checked_mpmc.rs
- curp/src/server/cmd_worker/mod.rs
- curp/src/server/curp_node.rs
- curp/src/server/mod.rs
- curp/src/server/raw_curp/mod.rs
- curp/tests/common/curp_group.rs
- curp/tests/server.rs
- xline/src/main.rs
- xline/src/server/xline_server.rs
publish the name of new node to cluster when node start
When a node starts, it publishes its name to the cluster by publish RPC, 
no
> feat: publish the name of new node to cluster when node start

- curp/src/members.rs
- curp/src/server/raw_curp/mod.rs
fix xline_add_node test
do not increase cluster_version when new node apply old conf changes
no
> fix: do not increase cluster_version when new node apply old conf changes

- .github/workflows/ci.yml
> ci: fix rust toolchain's version for cargo-outdated

- curp/src/client.rs
- curp/src/server/raw_curp/mod.rs
- xline/tests/it/cluster_test.rs
#531 
fix xline_update_node test
update node to an available address.
no
> fix: fix xline_update_node test and update comments

- curp/tests/it/read_state.rs
- test-macros/src/lib.rs
remove wrong message in abort_on_panic macro
remove wrong message in abort_on_panic macro
no
> fix: remove wrong message in abort_on_panic macro

- curp/src/client.rs
- curp/src/members.rs
- curp/src/rpc/connect.rs
- curp/src/rpc/mod.rs
- curp/src/server/curp_node.rs
I want to refactor the `set_cluster` function in current implementation, and I realized that I need to implement a single endpoint connection, then I refactor the connect from macros to function implementation.
As above.
No
> refactor: refactor connect from macros to function

- curp/src/server/cmd_worker/conflict_checked_mpmc.rs
- xline-client/src/clients/auth.rs
- xline-client/src/clients/kv.rs
- xline-client/src/clients/lease.rs
- xline-client/src/clients/lock.rs
- xline/src/server/auth_server.rs
- xline/src/server/command.rs
- xline/src/server/kv_server.rs
- xline/src/server/lease_server.rs
- xline/src/server/lock_server.rs
- xline/src/server/xline_server.rs
- xlineapi/src/command.rs
> fix: txn command key

- curp/src/client_new/unary.rs
- curp/src/members.rs
- curp/src/rpc/mod.rs
- curp/src/server/raw_curp/mod.rs
- curp/src/server/raw_curp/tests.rs
- curp/tests/it/server.rs
Solve https://github.com/xline-kv/Xline/pull/581#discussion_r1436447062
> fix: fix cluster version update

- curp/src/server/cmd_worker/mod.rs
- curp/src/server/raw_curp/mod.rs
- curp/src/server/raw_curp/tests.rs
Based on #566 
If we remove leader, the remaining nodes need to wait for the election timeout and elect a new leader.
move leadership when old leader shutdown 
no
> [Feature]: move leadership when old leader shutdown 

- curp/src/client/mod.rs
- curp/src/client/retry.rs
- curp/src/client/state.rs
- curp/src/client/tests.rs
- curp/src/client/unary.rs
- curp/src/rpc/connect.rs
Separate the client state from unary client to realize subsequent implementation of shared state between stream client and unary client.
Isolate client state.
No.
> refactor: isolate client state

- utils/src/config.rs
- xline/tests/it/maintenance_test.rs
unable to process requests normally without specifying leader to start the cluster
add longer timeout when there is no leader in cluster
no
> fix: longer timeout when there is no leader in cluster

- crates/xline/src/storage/kv_store.rs
- crates/xline/tests/it/kv_test.rs
return error if put kv with nonexistent lease id
return error if put kv with nonexistent lease id
no
> fix: return error if put kv with nonexistent lease id

- crates/curp/src/client/mod.rs
- crates/utils/src/config.rs
- crates/xline/src/main.rs
- crates/xline/src/metrics.rs
- crates/xline/src/utils/args.rs
- crates/xline/src/utils/trace.rs
refactor the `client-use-backoff` cmd line arg.
1. rename the `client-use-backoff` as `client-fixed-backoff` 
2. modify the type of `client-fixed-backoff` from Option<bool> to bool
3. modify the default value of `client-fixed-backoff`
> refactor: modify --client-use-backoff commandline arg

- crates/xline-client/README.md
The `README.md` file in `crates/xline-client` contains two incorrect hyperlinks, likely due to changes in the code structure.
Only modified the `README.md`
> docs: Fixed README redirection hyperlinks

- crates/curp/src/server/raw_curp/log.rs
Optimize the behavior of log append entries. Ref to #515
The behavior of log append entries was redudant and this pr has made optimization according to following steps:
1. Find the index of the first entry that needs to be truncated.
2. Record entries that need to be fallback in the truncated entries.
3. truncate entries
4. Push the remaining entries and record the conf change entries
No.
> refactor: improve append entries

- Cargo.lock
fix: https://rustsec.org/advisories/RUSTSEC-2024-0019
> chore: bump mio version to 0.8.11

- crates/xline/src/storage/kvwatcher.rs
Closes: #677
Add a HashSet to track all notified revision. 
> fix: xline watcher will loss event

- doc/quick-start/README.md
This PR resolved this issue https://github.com/xline-kv/Xline/issues/693
Documentation change for quick-start
Correct the quick-start DOC path to copy private and public pem file to scripts
NO
> fix: quick-start readme corrected pem file path

- crates/xline/src/utils/args.rs
This PR resolved this issue: https://github.com/xline-kv/Xline/issues/691
During the startup process of Xline, certain essential command-line parameters such as --member and --storage-engine are checked. and there is a lack of validation for `--client-listen-urls `and `--peer-listen-urls`
Here's how it looks -
> feat: Added validation for --client-listen-urls and --peer-listen-urls

- .github/dependabot.yml
Let dependabot work for auto update github-actions to get rid of deprecated github actions.
Also can update it for argo if you accepts the automatic update of cargo dependencies,
```yaml
- package-ecosystem: "cargo"
directory: "/"
schedule:
interval: "weekly"
labels:
- "dependencies"
```
> chore: Add config for dependabot.

- crates/utils/src/interval_map/mod.rs
- crates/xlineapi/src/interval.rs
- crates/xlineapi/src/lib.rs
Based on: #656 
Adds a new type `BytesAffine`, which defines the order of the keys. 
FYI: 
- https://etcd.io/docs/v3.3/learning/api/#key-ranges
- https://github.com/etcd-io/etcd/blob/e68afe7eb7ce3e5f83deb2a8ad58faa3b35494b9/pkg/adt/interval_tree.go#L919-L947
> feat: Add bytes affine

- crates/curp-external-api/src/conflict.rs
- crates/curp-external-api/src/lib.rs
- crates/curp/src/rpc/mod.rs
- crates/curp/src/server/conflict/mod.rs
- crates/curp/src/server/conflict/spec_pool_new.rs
- crates/curp/src/server/conflict/tests.rs
- crates/curp/src/server/conflict/uncommitted_pool.rs
- crates/curp/src/server/mod.rs
- crates/curp/src/server/raw_curp/mod.rs
- crates/curp/src/server/spec_pool.rs
First PR of #668.
Implements new speculative pool and uncommitted pool in curp.
> feat: New curp conflict pool

- Cargo.lock
- crates/curp-test-utils/src/test_cmd.rs
- crates/curp/src/server/cmd_worker/mod.rs
- crates/curp/src/server/conflict/spec_pool_new.rs
- crates/curp/src/server/conflict/tests.rs
- crates/curp/src/server/conflict/uncommitted_pool.rs
- crates/curp/src/server/curp_node.rs
- crates/curp/src/server/raw_curp/mod.rs
- crates/curp/tests/it/server.rs
- crates/engine/Cargo.toml
- crates/engine/src/memory_engine/mod.rs
- crates/engine/src/rocksdb_engine/mod.rs
- crates/utils/src/task_manager/mod.rs
- crates/xline-client/src/clients/auth.rs
- crates/xline-client/src/clients/kv.rs
- crates/xline/src/server/command.rs
- crates/xline/src/storage/auth_store/store.rs
- crates/xline/src/storage/kv_store.rs
- crates/xline/src/storage/lease_store/lease_collection.rs
- crates/xline/src/storage/lease_store/mod.rs
- crates/xline/src/utils/args.rs
- crates/xlinectl/src/command/watch.rs
- crates/xlinectl/src/utils/parser.rs
Refs: #774
Closes: #774
FYI: #774 
Add a retry logic in `write_batch`.
There is nothing to change breakingly, but we need to do a performance regression test for this modification.
> fix: add txn retry logic

- Cargo.lock
- crates/curp/Cargo.toml
- crates/curp/src/rpc/mod.rs
- crates/curp/src/server/conflict/mod.rs
- crates/curp/src/server/conflict/test_pools.rs
- crates/xline/Cargo.toml
- crates/xline/src/conflict/mod.rs
- crates/xline/src/conflict/spec_pool.rs
- crates/xline/src/conflict/tests.rs
- crates/xline/src/conflict/uncommitted_pool.rs
- crates/xline/src/lib.rs
- crates/xlineapi/src/command.rs
This PR implements the conflict pool data structures in xline. 
> refactor: implement xline conflict pools

- crates/utils/src/config.rs
-> Fixes #649 
-> Change default `rpc_timeout` to 150ms to prevent the warn of ae failed in tests, which was caused by the scheduling of simulation.
No
> fix:change rpc timeout to prevent the warn of ae failed

- crates/curp/src/server/storage/wal/codec.rs
- crates/curp/src/server/storage/wal/error.rs
- crates/curp/src/server/storage/wal/framed.rs
- crates/curp/src/server/storage/wal/mod.rs
- crates/curp/src/server/storage/wal/pipeline.rs
- crates/curp/src/server/storage/wal/segment.rs
- crates/curp/src/server/storage/wal/util.rs
Switch the curp WAL to synchronous implementation, as the current async version is slow in benchmarks.
> refactor: switch wal to sync implementation

- .github/workflows/docker_image.yml
Push the latest image for let people can be experience the master branch function in advance.
> Push the latest image on push master.

- crates/engine/src/memory_engine/mod.rs
- crates/engine/src/memory_engine/transaction.rs
Depends-On: #674 
Implement txn API for memory engine.
> feat: implement memory transaction

- .github/dependabot.yml
- .github/workflows/stale.yml
Currently, our depend-bot update is a little bit frequent, therefore I reduce the `open-pull-requests-limit` from 10 to 3 per week.
1. reduce the `open-pull-requests-limit` from 10 to 3 per week.
2. update the correct release slash-assign-action
> ci: update workflow

- crates/curp/tests/it/common/curp_group.rs
- crates/curp/tests/it/server.rs
- crates/utils/src/task_manager/tasks.rs
Using a notify logic to instead the sleep logic in some integration test cases
> refactor: remove sleep_secs method when waiting the cluster to shutdown

- crates/curp/src/server/storage/wal/mod.rs
- crates/curp/src/server/storage/wal/remover.rs
Depends-on: #705 
Implement WAL segment remover, the segment remover is used to make sure a wal segment file is atomically removed.
> feat: implement WAL segments remover

- .github/dependabot.yml
- .github/workflows/docker_image.yml
- .github/workflows/merge_image.yml
- .github/workflows/release.yml
artifact v4 do not support upload artifact with the same name, https://github.com/actions/upload-artifact?tab=readme-ov-file#not-uploading-to-the-same-artifact , so this PR is working for downgrade v4 to v3, until we get rid of using github jobs to build multi-architecture container images.
so release workflow is also broken, https://github.com/xline-kv/Xline/blob/dca44495673ab0cf4c67ecb59110bbddcde22c74/.github/workflows/release.yml#L144
> chore: downgrade github artifact to v3 from v4 for publish docker image.

- crates/curp/src/server/storage/wal/codec.rs
- crates/curp/src/server/storage/wal/pipeline.rs
- crates/curp/src/server/storage/wal/segment.rs
> refactor: use reference type in DataFrame

- crates/curp/src/client/unary.rs
close #825 
Return early in fast_round if the KeyConflicts number is greater than or equal to the recovery quorum.
> feat: return early in fast_round if the recover_quorum condition is not met

- Cargo.lock
- Cargo.toml
- crates/benchmark/Cargo.toml
- crates/xline/Cargo.toml
> chore: bump etcd-client to 0.13.0

- crates/curp/src/server/curp_node.rs
- crates/curp/src/server/mod.rs
- crates/curp/src/server/raw_curp/log.rs
- crates/curp/src/server/raw_curp/mod.rs
- crates/curp/src/server/storage/wal/segment.rs
-> Fixes #368 
-> Use a scrolling array to replace the previous prefix array to prevent `batch_index ` overflow, which will be truncated when compact. Besides, the scrolling array reduces the operation time complexity of obtaining batch log to O(1).
-> No
> fix: prevent batch_index overflow in raw_curp

- Cargo.lock
- crates/utils/Cargo.toml
- crates/utils/src/config.rs
- crates/utils/src/parser.rs
- crates/xline/src/utils/args.rs
- crates/xline/src/utils/trace.rs
- scripts/common.sh
- scripts/quick_start.sh
- scripts/validation_test.sh
- what problem are you trying to solve? (or if there's no problem, what's the motivation for this change?)
-> Fixes #670 
-> Currently, Xline does not support redirecting the logs to the terminal. It  outputs to a specified log file through `--log-file` in command line. If the user does not specify this parameter, the file path `/var/log/xline` is created by default.
- what changes does this pull request make?
-> Checks whether the user specifies  `--log-file`. If not, output the logs to the terminal and ignore `--log-rotate` if provided.
- are there any non-obvious implications of these changes? (does it break compatibility with previous versions, etc)
-> No
> feat: support redirecting the logs to the terminal

- crates/curp/src/client/tests.rs
Update testing logic to keep aligned with early return in fast path.
**Since we can return early in fast path when the number of conlicts is so large that we cannot reach SuperQuorum.**
So we **DO NOT NEED to force** all the 5 servers to handle the propose. 
related issue : #840 
Remove the counter, and the rest part works fine (Successfully fallback to slow path) .
> fix: remove counter to keep aligned with early return in fast path

- Cargo.lock
- crates/utils/Cargo.toml
- crates/utils/src/barrier.rs
- crates/utils/src/lib.rs
- crates/xline/src/server/barriers.rs
- crates/xline/src/server/command.rs
- crates/xline/src/server/kv_server.rs
- crates/xline/src/server/xline_server.rs
> feat: move id barrier to utils

- crates/xline/src/server/auth_server.rs
- crates/xline/src/server/auth_wrapper.rs
- crates/xline/src/server/command.rs
- crates/xline/src/server/kv_server.rs
- crates/xline/src/server/lease_server.rs
- crates/xline/src/server/lock_server.rs
- crates/xline/src/server/maintenance.rs
- crates/xline/src/server/watch_server.rs
- crates/xline/src/server/xline_server.rs
- crates/xline/src/state.rs
- crates/xline/src/storage/alarm_store.rs
- crates/xline/src/storage/auth_store/backend.rs
- crates/xline/src/storage/auth_store/store.rs
- crates/xline/src/storage/compact/mod.rs
- crates/xline/src/storage/db.rs
- crates/xline/src/storage/kv_store.rs
- crates/xline/src/storage/kvwatcher.rs
- crates/xline/src/storage/lease_store/mod.rs
- crates/xline/src/storage/mod.rs
- crates/xline/src/storage/revision.rs
- crates/xline/src/storage/storage_api.rs
The DB generic is redundant as no other type will ever implement `StorageApi` in Xline. This change aims to enhance readability of the codebase.
> refactor: remove DB generic

- crates/curp-external-api/src/cmd.rs
- crates/curp-test-utils/src/test_cmd.rs
- crates/xline-client/src/clients/auth.rs
- crates/xline-client/src/clients/kv.rs
- crates/xline-client/src/clients/lease.rs
- crates/xline-client/src/clients/lock.rs
- crates/xline/src/conflict/tests.rs
- crates/xline/src/server/auth_server.rs
- crates/xline/src/server/command.rs
- crates/xline/src/server/kv_server.rs
- crates/xline/src/server/lease_server.rs
- crates/xline/src/server/lock_server.rs
- crates/xline/src/server/maintenance.rs
- crates/xline/src/storage/compact/mod.rs
- crates/xline/src/storage/lease_store/mod.rs
- crates/xlineapi/src/command.rs
- crates/xlineapi/src/lib.rs
The keys are not necessary in serialization, we could generate keys only when being used.
> refactor: remove keys from command

- crates/curp/src/server/storage/wal/config.rs
- crates/curp/src/server/storage/wal/error.rs
- crates/curp/src/server/storage/wal/mod.rs
- crates/curp/src/server/storage/wal/segment.rs
- crates/curp/src/server/storage/wal/test_util.rs
- crates/curp/src/server/storage/wal/tests.rs
Depends-On: #740 
This is part of the wal implementation, which implements the WAL storage type
> feat: implement curp wal storage

- crates/curp/src/server/storage/wal/codec.rs
- crates/curp/src/server/storage/wal/pipeline.rs
- crates/curp/src/server/storage/wal/segment.rs
Depends-On: #687 
Some fixes and improvements for the WAL storage
> fix: curp wal

- crates/xline/src/server/command.rs
- crates/xline/src/server/watch_server.rs
- crates/xline/src/storage/compact/mod.rs
- crates/xline/src/storage/index.rs
- crates/xline/src/storage/kv_store.rs
- crates/xline/src/storage/kvwatcher.rs
> refactor: Index

- crates/engine/src/lib.rs
- crates/xline/src/server/command.rs
- crates/xline/src/server/watch_server.rs
- crates/xline/src/storage/auth_store/backend.rs
- crates/xline/src/storage/db.rs
- crates/xline/src/storage/kv_store.rs
- crates/xline/src/storage/kvwatcher.rs
- crates/xline/src/storage/lease_store/mod.rs
- crates/xline/src/storage/mod.rs
- crates/xline/src/storage/storage_api.rs
Depends-On: #673 #806 
Adds an `XlineStorageOps` trait as a replacement to `StorageApi` which is removed in #806
> refactor: xline storage api

- crates/xlinectl/README.md
- crates/xlinectl/src/command/lock.rs
- scripts/validation_test.sh
To solve issue: #823 
Change the `xlinectl lock` command
> feat: add exec command support for xlinectl lock

- crates/benchmark/src/bench_client.rs
- crates/benchmark/src/runner.rs
- crates/simulation/src/xline_group.rs
- crates/simulation/tests/it/xline.rs
- crates/xline-client/examples/error_handling.rs
- crates/xline-client/examples/kv.rs
- crates/xline-client/examples/lock.rs
- crates/xline-client/examples/watch.rs
- crates/xline-client/src/clients/kv.rs
- crates/xline-client/src/types/kv.rs
- crates/xline-client/tests/it/kv.rs
- crates/xline-client/tests/it/watch.rs
- crates/xline/tests/it/auth_test.rs
- crates/xline/tests/it/cluster_test.rs
- crates/xline/tests/it/kv_test.rs
- crates/xline/tests/it/lease_test.rs
- crates/xline/tests/it/maintenance_test.rs
- crates/xline/tests/it/tls_test.rs
- crates/xline/tests/it/watch_test.rs
- crates/xlinectl/src/command/put.rs
- crates/xlinectl/src/command/txn.rs
- one of the series of #819 refactor, to remove request wrappers in xline-client and make user interface easier to use.
- change function in `clients/kv.rs` from `fn put(&self, request: PutRequest)` to `put(&self, key: impl Into<Vec<u8>>, value: impl Into<Vec<u8>>, option: Option<PutOptions>)`
- Renames `types::PutRequest` to `types::PutOptions`, made it an option for put function. The option will be combined with key and value to a `xlineapi::PutRequest` inside the `KvClient.put()` function.
-  If it gets a None, construct a default PutOptions instead.
- TxnOp::put function has been changed as well.
* …
> refactor(client)!: Remove request wrappers - KvClient::put

- crates/xline-client/src/clients/auth.rs
- crates/xline-client/src/lib.rs
- crates/xline-client/src/types/auth.rs
- one of the series of #819 refactor, to remove request wrappers in xline-client and make user interface easier to use.
- change function in `clients/auth.rs` from `fn authenticate(&mut self, request: AuthenticateRequest)` to `fn authenticate(&mut self, name: impl Into<String>, password: impl Into<String>)`
- remove `struct AuthenticateRequest`
- yes, it's a breaking change and may break code uses old version of `authenticate()`.
> refactor(client)!: Remove request wrappers - AuthClient::authenticate

- crates/curp-external-api/src/cmd.rs
- crates/curp-test-utils/src/test_cmd.rs
- crates/curp/src/server/cmd_worker/mod.rs
- crates/curp/src/server/storage/wal/codec.rs
- crates/xline/src/revision_number.rs
- crates/xline/src/server/command.rs
- crates/xline/src/server/kv_server.rs
- crates/xline/src/server/watch_server.rs
- crates/xline/src/server/xline_server.rs
- crates/xline/src/storage/alarm_store.rs
- crates/xline/src/storage/auth_store/store.rs
- crates/xline/src/storage/compact/revision_compactor.rs
- crates/xline/src/storage/kv_store.rs
- crates/xline/src/storage/kvwatcher.rs
- crates/xline/src/storage/lease_store/mod.rs
- crates/xlineapi/src/lib.rs
Depends-On: #687 #807 #673 #853 
This PR refactors xline kv storage and xline command executor.
Some tests will not be fixed in this PR; they will be fixed in #821.
> refactor: xline command execution

- crates/curp/src/server/curp_node.rs
- crates/curp/src/server/mod.rs
- crates/curp/tests/it/common/curp_group.rs
- crates/xline/src/server/xline_server.rs
This pr adds the cmd executor to a field of `CurpNode`
> reafctor: add CE to CurpNode

- .github/workflows/pull_request.yml
- ci does not test doc
- add a doc test
- note that [nextest does not support doc test](https://nexte.st/docs/running/#fn:doctest). [ref](https://github.com/nextest-rs/nextest/issues/16)
- no
> fix(ci): add doc test

- crates/xline-client/examples/auth_user.rs
- crates/xline-client/src/clients/auth.rs
- crates/xline-client/src/types/auth.rs
- crates/xline-client/tests/it/auth.rs
- crates/xline-test-utils/src/lib.rs
- crates/xline/tests/it/auth_test.rs
- crates/xlinectl/src/command/user/add.rs
- one of the series of #819 refactor, to remove request wrappers in xline-client and make user interface easier to use.
- change `fn user_add(&self, mut request: AuthUserAddRequest)` to `user_add(&self, name: impl Into<String>,  password: impl AsRef<str>, options: Option<xlineapi::UserAddOptions>)`
- remove `types::AuthUserAddRequest`
- yes, it's a breaking change and may break code uses old version of `user_add()`.
> refactor(client)!: Remove request wrappers - AuthClient::user_add

- crates/xline-client/examples/auth_user.rs
- crates/xline-client/src/clients/auth.rs
- crates/xline-client/src/types/auth.rs
- crates/xline-client/tests/it/auth.rs
- crates/xline/tests/it/auth_test.rs
- crates/xlinectl/src/command/user/get.rs
- one of the series of #819 refactor
- change `user_get(&self, request: AuthUserGetRequest)` to `user_get(&self, name: impl Into<String>)`
- remove `types::AuthUserGetRequest`
- yes, it's a breaking change and may break code uses old version of `user_get()`.
> refactor(client)!: Remove request wrappers - AuthClient::user_get

- crates/xline-client/examples/auth_user.rs
- crates/xline-client/src/clients/auth.rs
- crates/xline-client/src/types/auth.rs
- crates/xline-client/tests/it/auth.rs
- crates/xlinectl/src/command/user/delete.rs
- one of the series of #819 
- change `user_delete(&self, request: AuthUserDeleteRequest)` to `user_delete(&self, name: impl Into<String>)`
- remove `types::AuthUserDeleteRequest`
- yes, it's a breaking change and may break code uses old version of `user_delete()`.
> refactor(client)!: Remove request wrappers - AuthClient::user_delete

- crates/curp/src/client/mod.rs
- crates/curp/src/client/retry.rs
- crates/curp/src/client/state.rs
- crates/curp/src/client/stream.rs
- crates/curp/src/client/tests.rs
- crates/curp/src/rpc/mod.rs
- crates/curp/tests/it/common/curp_group.rs
- crates/simulation/src/curp_group.rs
Make it competible with gRPC implementations that do not support the `optional` keyword
> refactor: use a custom `OptionalU64` to replace Option<u64>

- crates/xline-client/examples/auth_user.rs
- crates/xline-client/src/clients/auth.rs
- crates/xline-client/src/types/auth.rs
- crates/xline-client/tests/it/auth.rs
- crates/xlinectl/src/command/user/passwd.rs
Depends-On: #882 
- change `user_change_password(&self,mut request: AuthUserChangePasswordRequest)` to `user_change_password(&self,name: impl Into<String>,password: impl AsRef<str>)`
- remove `types::AuthUserChangePasswordRequest`
- yes
> refactor(client)!: refactor AuthClient::user_change_password

- crates/xline-client/examples/auth_role.rs
- crates/xline-client/src/clients/auth.rs
- crates/xline-client/src/types/auth.rs
- crates/xline-client/tests/it/auth.rs
- crates/xlinectl/src/command/role/get.rs
- crates/xlinectl/src/command/user/get.rs
> refactor(client)!: Remove request wrappers - AuthClient::role_get

- crates/simulation/src/xline_group.rs
- crates/simulation/tests/it/xline.rs
- crates/xline-client/examples/watch.rs
- crates/xline-client/src/clients/lock.rs
- crates/xline-client/src/clients/watch.rs
- crates/xline-client/src/types/mod.rs
- crates/xline-client/src/types/range_end.rs
- crates/xline-client/src/types/watch.rs
- crates/xline-client/tests/it/watch.rs
- crates/xline/src/server/lock_server.rs
- crates/xline/tests/it/watch_test.rs
- crates/xlineapi/src/command.rs
- crates/xlinectl/src/command/watch.rs
Depends-On: #905 
- use `enum WatchKeyOptions` to record `with_prefix` and `with_from_key` because when constructing `WatchRequest`, the key is not given.
> refactor(client)!: Remove request wrappers - WatchClient::watch

- Cargo.lock
- crates/curp/src/client/retry.rs
- crates/curp/src/client/state.rs
- crates/curp/src/client/tests.rs
- crates/curp/src/client/unary.rs
- crates/curp/src/lib.rs
- crates/curp/src/log_entry.rs
- crates/curp/src/response.rs
- crates/curp/src/rpc/connect.rs
- crates/curp/src/rpc/mod.rs
- crates/curp/src/server/cmd_board.rs
- crates/curp/src/server/cmd_worker/mod.rs
- crates/curp/src/server/curp_node.rs
- crates/curp/src/server/mod.rs
- crates/curp/src/server/raw_curp/log.rs
- crates/curp/src/server/raw_curp/mod.rs
- crates/curp/src/server/raw_curp/tests.rs
- crates/curp/tests/it/common/curp_group.rs
- crates/curp/tests/it/read_state.rs
- crates/curp/tests/it/server.rs
- crates/simulation/src/curp_group.rs
- crates/utils/src/task_manager/mod.rs
- crates/utils/src/task_manager/tasks.rs
- crates/xline/Cargo.toml
- crates/xline/src/server/auth_wrapper.rs
Depends-On: #917
This PR reimplements the client propose process on both curp server and client.
This refactor includes:
- Use serial execution for execute and after sync
- Curp client will now use a gRPC stream for propose(Remove of `WaitSyncedRequest`).
- Use `Record` rpc to record to speculative pools (witnesses)
> refactor: reimplement client propose in curp

- .github/workflows/benchmark.yml
- .github/workflows/build_env.yml
- .github/workflows/build_xline.yml
- .github/workflows/pull_request.yml
- .github/workflows/validation.yml
- Cargo.toml
- ci/Dockerfile
- The CI failed a lot of time without error message, and it's not problem of code. When retry, the ci may pass, or fail as same.
- related ci: https://github.com/xline-kv/Xline/actions/runs/10209311482/job/28247138131?pr=880
- after one failure, i captured the output of github: 
- ~~introduce [free-disk-space](https://github.com/marketplace/actions/free-disk-space-ubuntu)~~
- mount some big dirs to image, and delete them manually.
- use sccache action instead of set up variables manually.
* are there any non-obvious implications of these changes? (does it break compatibility with previous versions, …
> fix(ci): free disk space to avoid CI runs out of space problem

- crates/curp-external-api/src/cmd.rs
- crates/curp-test-utils/src/test_cmd.rs
- crates/curp/src/client/state.rs
- crates/curp/src/client/stream.rs
- crates/curp/src/server/cmd_worker/mod.rs
- crates/simulation/tests/it/curp/server_recovery.rs
- crates/xline/src/server/command.rs
- crates/xline/src/server/watch_server.rs
- crates/xline/src/server/xline_server.rs
- crates/xline/src/storage/compact/mod.rs
- crates/xline/src/storage/kv_store.rs
- crates/xline/src/storage/kvwatcher.rs
- crates/xline/src/storage/lease_store/mod.rs
- crates/xline/tests/it/kv_test.rs
This PR introduces the following major changes:
- Switch after sync to sync version (previously async)
- Rewrite error returning mechanism during after sync stage
During the after sync execution (in `crates/xline/src/server/command.rs`), we use batch persistent, and this will introduce two types of errors
- a execution error for a single command
- a batch persistent error
Thus, we cannot return immediately after encounter and error, but need to record the execution result for each command. A `ASResultStates` type is introduced to resolve this issue.
* are there any non-obvious implications of these …
> refactor: after sync implementation

- crates/curp/src/client/mod.rs
- crates/curp/src/server/raw_curp/mod.rs
- crates/simulation/src/curp_group.rs
- crates/simulation/tests/it/curp/server_recovery.rs
- crates/xline/src/storage/kv_store.rs
Depends-On: #938
Some assumptions of the madsim tests have changed. I rewrote some tests to meet the new refactor's assumptions.
Some of the new assumptions:
- follower does not need to execute the command
- the `ProposeRequest` will only be sent to the leader, the `RecordRequest` will be sent to the followers.
Other changes:
- We need to use the client id generated from the server to build a `ProposeId`, otherwise the server would reject the propose.
> fix: madsim tests

- crates/xline-client/src/clients/maintenance.rs
- crates/xline-client/src/types/maintenance.rs
- crates/xline-client/src/types/mod.rs
- crates/xline/tests/it/maintenance_test.rs
- one of the series of #819 refactor, to remove request wrappers in xline-client and make user interface easier to use.
> refactor(client)!: Remove request wrappers - MaintenanceClient::alarm

- crates/xline-client/examples/auth_role.rs
- crates/xline-client/src/clients/auth.rs
- crates/xline-client/src/types/auth.rs
- crates/xline-client/tests/it/auth.rs
- crates/xline-test-utils/src/lib.rs
- crates/xlinectl/src/command/role/grant_perm.rs
> refactor(client)!: Remove request wrappers - AuthClient::role_grant_permission

- crates/curp/src/server/cmd_board.rs
- crates/curp/src/server/cmd_worker/mod.rs
- crates/curp/src/server/curp_node.rs
- crates/curp/src/server/mod.rs
- crates/curp/src/server/raw_curp/mod.rs
In normal propose path, the leader maintains a gRPC stream to the client. However, if the leader crashes and a new leader is elected, the client won't be able to retrive the previous result.
This PR makes the leader record the er and asr results to the cmd board and they will be returned to the client on next retry.
> refactor: record er and asr for recovered commands

- crates/curp/src/server/curp_node.rs
- crates/curp/src/server/gc.rs
- crates/curp/src/server/raw_curp/mod.rs
This PR refactored the GC of the cmd board. Commands will only be removed after their client lease has expired.
> refactor: cmd board gc

- crates/curp/src/client/tests.rs
- crates/curp/src/client/unary.rs
- crates/curp/src/rpc/connect.rs
- crates/curp/src/rpc/mod.rs
- crates/curp/src/server/cmd_worker/mod.rs
- crates/curp/src/server/curp_node.rs
- crates/curp/src/server/mod.rs
- crates/curp/src/server/raw_curp/mod.rs
- crates/curp/src/server/raw_curp/state.rs
- crates/utils/src/barrier.rs
- crates/xline/src/server/auth_wrapper.rs
This PR implements the read index mechanism described in the Raft paper.
The implementation is differs slightly from the original algorithm. In this implementation, the client is responsible for broadcasting the `ReadIndex` request to the cluster. This modification reduces latency to 1RTT for non-conflicting read-only commands.
> feat: implement read index

- crates/curp-external-api/src/cmd.rs
- crates/curp-test-utils/src/test_cmd.rs
- crates/curp/src/client/unary.rs
- crates/curp/src/server/cmd_worker/mod.rs
- crates/curp/src/server/curp_node.rs
- crates/curp/src/server/gc.rs
- crates/utils/src/task_manager/tasks.rs
- crates/xline/src/server/command.rs
Depends-On: #949 
This PR fixes read only commands execution. 
Currently read only commands won't go through the after sync phase. However, for etcd compatible API, the revision in after sync result must be returned to the client.
> fix: after sync result of read only commands

- crates/utils/src/lca_tree.rs
- crates/utils/src/lib.rs
- crates/xlineapi/src/request_validation.rs
#410 
Corrected the behavior of request validation. Please refer to this [proposal](https://gg2002.github.io/2024/03/02/gsoc-2024-proposal/) for the general idea. The specific code behavior is slightly different from what is stated in the proposal, but the idea of finding out LCA is the same.
No.
Reopen #942
> fix: correct request validation

- crates/xline-client/examples/auth_role.rs
- crates/xline-client/src/clients/auth.rs
- crates/xline-client/src/types/auth.rs
- crates/xline-client/tests/it/auth.rs
- crates/xlinectl/src/command/role/revoke_perm.rs
> refactor(client)!: Remove request wrappers - AuthClient::role_revoke_permission

- crates/utils/Cargo.toml
Refer to #960. Add a clear version number to eliminate RA warnings.
> chore: add version number to eliminate RA warnings

- crates/utils/src/parser.rs
- crates/xline/src/utils/trace.rs
> refactor: enable setting xline log level using `RUST_LOG` env

- .github/ISSUE_TEMPLATE/bug_report.yaml
> chore: remove trailing space in bug_report.yaml

- crates/curp/src/client/mod.rs
- crates/curp/src/client/tests.rs
- crates/curp/src/client/unary/mod.rs
- crates/curp/src/client/unary/propose_impl.rs
- crates/curp/src/response.rs
- crates/curp/src/server/cmd_worker/mod.rs
- crates/curp/src/server/curp_node.rs
This PR includes several changes:
* Moves client propose code to a seperate module `propose_impl`
* Improve propose latency for mutative commands
This is done by simultaneously waitting for the `record` request to the cluster and the message from the leader gRPC stream.
> refactor: curp client propose

- USAGE.md
- crates/utils/README.md
- crates/xline-client/README.md
- crates/xlinectl/README.md
- crates/xlineutl/README.md
- dead link or missing link exists
- fix dead link and missing link
- make options more readable by adding back quotes (``` ` ```)
- reformat some markdown file using [Prettier](https://prettier.io/)
- no
> docs: multiple markdown docs fixed

- crates/curp/src/lib.rs
- crates/curp/src/server/mod.rs
- crates/curp/src/server/raw_curp/log.rs
- crates/xline-client/src/clients/kv.rs
- crates/xline-client/src/clients/lease.rs
- crates/xline/src/storage/compact/periodic_compactor.rs
- redundant `.field` in `KvClient` and `LeaseClient`
1. remove redundant `.field` in `KvClient` and `LeaseClient`
2. add a missing test case for `quorum_should_work()` test, corresponding to the above node(10).
3. (trivial) change for loop to sum() in `raw_curp/log.rs`
- no
> chore: code fixing, remove redundant and add missing

- crates/curp/tests/it/server.rs
- close #907
- modify `shutdown_rpc_should_shutdown_the_cluster()`: make put thread return faster when retry count up to max times.
- make another task manager panic bug #919 more often to happen.
> fix: shutdown cluster test timeout

- Cargo.lock
- crates/curp/src/client/mod.rs
- crates/curp/src/client/retry.rs
- crates/curp/src/client/state.rs
- crates/curp/src/client/tests.rs
- crates/curp/src/client/unary/mod.rs
- crates/curp/src/members.rs
- crates/curp/src/rpc/connect.rs
- crates/curp/src/rpc/mod.rs
- crates/curp/src/rpc/reconnect.rs
- crates/curp/src/server/curp_node.rs
- crates/curp/src/server/mod.rs
- crates/curp/tests/it/common/curp_group.rs
- crates/curp/tests/it/server.rs
- crates/simulation/src/curp_group.rs
- crates/simulation/tests/it/curp/server_recovery.rs
- crates/xline-client/src/lib.rs
- crates/xline/src/server/xline_server.rs
- crates/xline/tests/it/lock_test.rs
This PR includes two major changes:
* Implements an auto reconnect layer.
* Lazily build connections for client.
> refactor: add auto reconnect to curp client
