curp/Cargo.toml
curp/doc/steps.md
curp/src/main.rs
xline/src/main.rs

The recovery part is not complete

Add curp steps

---

.github/workflows/ci.yml
curp/Cargo.toml
curp/proto/message.proto
curp/src/client.rs
curp/src/rpc.rs
curp/src/server.rs
curp/src/sync_manager.rs
curp/tests/common/mod.rs
curp/tests/speculative_execute.rs
curp/tests/synced_propose.rs
xline/src/main.rs
xline/src/server/xline_server.rs
xline/tests/common/mod.rs
xline/tests/kv_test.rs

1. Refactor the msg broadcast logic
2. Make kv tests parallel runnable

Some refators

---

curp/src/server.rs
xline/src/server/command.rs
xline/src/storage/db.rs
xline/src/storage/index.rs
xline/src/storage/kvstore.rs
xline/tests/kv_test.rs

combine get_one and get_one_from_rev

support range request with revision

---

curp/src/channel/key_mpsc.rs
curp/src/channel/key_spmc.rs
curp/src/channel/mod.rs
curp/src/client.rs
curp/src/cmd.rs
curp/src/rpc.rs
curp/src/server.rs
curp/src/sync_manager.rs

Fix typos, grammar errors, and some minor refactoring when I am studying the code.

Fix typos, grammar errors, and some minor refactoring

---

.github/workflows/docker.yml
.mergify.yml
curp/src/channel/key_mpsc.rs
curp/src/channel/key_spmc.rs
curp/src/server.rs

fix clippy errors
add required env to docker.yml
add ci checks to .mergify.yml

fix some errors

---

CONTRIBUTING.md

Adding some dependencies information for building the latest protoc from the source code. Extracting them into a new section to make the doc structure neater.

adding a dependencies section in CONTRIBUTING.md

---

curp/src/client.rs
curp/src/rpc.rs
curp/src/server/mod.rs
curp/src/util.rs
rust-toolchain.toml
xline/src/main.rs
xline/src/server/auth_server.rs
xline/src/server/kv_server.rs
xline/src/server/lease_server.rs
xline/src/server/lock_server.rs
xline/src/server/watch_server.rs
xline/src/storage/kvstore.rs

replace all logs with tracing
simplify injection and extraction of spans
optimize connect send request
add rust-toolchain file

refactor for tracing

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/PULL_REQUEST_TEMPLATE.md
README.md
curp/src/server/cmd_board.rs
xline/src/storage/authstore/perms.rs
xline/src/storage/authstore/store.rs

update the `Roadmap` section in README.md and add a pr and some issue template files

Update readme doc and add some template files

---

xline/src/storage/authstore/backend.rs

Using AtomicBool to replace Mutex<bool> in the `AuthStoreBackend` definition. There is no need to use mutex here. Using AtomicBool would be better.

using AtomicBool to replace Mutex<bool> for better efficiency

---

CONTRIBUTING.md
QUICK_START.md
README.md

Update the contributing guide doc.
Update the contributing guide doc. 
No

update the contributing guide doc

---

.github/workflows/benchmark.yml
.github/workflows/coverage.yml
.github/workflows/docker.yml
USAGE.md
benchmark/src/args.rs
scripts/benchmark.sh
scripts/quick_start.sh

fix scripts, docs and CI after refactor args
fix bugs
No

fix scripts, docs and CI

---

CHANGELOG.md
MAINTAINERS
VALIDATION_REPORT.md

Update CHANGELOG.md for the new release v0.2.0 publishing

update CHANGELOG.md for release v0.2.0

---

curp/src/client.rs
curp/src/lib.rs
curp/src/server/bg_tasks.rs
curp/src/server/mod.rs
curp/src/server/state.rs
curp/tests/server_election.rs
scripts/coverage.sh
utils/src/config.rs
xline/src/main.rs
xline_server.conf

[Curp] Employ tick mechanism

---

curp/src/server/bg_tasks.rs
curp/src/server/cmd_worker.rs
curp/src/server/mod.rs
curp/src/server/state.rs

The first PR described in #169. Based on #165.

[Curp] Refactor cmd worker

---

USAGE.md
curp/src/client.rs
utils/src/config.rs
xline/src/main.rs
xline/src/server/kv_server.rs
xline/src/storage/kv_store.rs

add configuration doc and their default values in `USAGE.md`.
#155 
add doc about the configuration file

Add config doc

---

xline/src/rpc/mod.rs
xline/src/server/command.rs
xline/src/server/lease_server.rs
xline/src/server/xline_server.rs
xline/src/storage/db.rs
xline/src/storage/lease_store/lease.rs
xline/src/storage/lease_store/mod.rs

based on #170 
our lease is not persist now, we need to add this
add persistence of lease
no

Persist lease

---

.github/workflows/validation.yml

Fix mergify bot not automatically merge

---

.github/workflows/ci.yml
.github/workflows/validation.yml

Use GitHub cache action to speed up our workflows.

add cache action to speed up github action workflow

---

curp/src/client.rs
curp/src/cmd.rs
curp/src/lib.rs
curp/src/server/cmd_board.rs
curp/src/server/cmd_worker/conflict_checked_mpmc.rs
curp/src/server/cmd_worker/mod.rs
curp/src/server/curp_node.rs
curp/src/server/mod.rs
curp/src/server/raw_curp/mod.rs
curp/src/server/raw_curp/tests.rs
curp/src/server/spec_pool.rs
curp/src/test_utils/test_cmd.rs
curp/tests/common/test_cmd.rs

Previously, we use two channel to track cmd exe and as progress. We can change the msg conflict check based mpmc to cmd conflict check based mpmc. It's easier to understand and will make it easy for our snapshot support.
conflict_checked mpmc

refactor mpmc channel

---

curp/src/cmd.rs
engine/src/engine_api.rs
engine/src/memory_engine.rs
xline/src/rpc/mod.rs
xline/src/server/command.rs
xline/src/server/xline_server.rs
xline/src/storage/auth_store/backend.rs
xline/src/storage/auth_store/mod.rs
xline/src/storage/auth_store/store.rs
xline/src/storage/db.rs
xline/src/storage/kv_store.rs
xline/src/storage/lease_store/message.rs
xline/src/storage/lease_store/mod.rs
xline/src/storage/revision.rs
xline/src/storage/storage_api.rs

Refactor: kv&lease store

---

.github/workflows/release.yml
CHANGELOG.md

Update CHANGELOG.md for release v0.3.0.
Add a release workflow to upload the release.

Release Xline v0.3.0

---

.github/workflows/release.yml

correct rust toolchain version in release.yml

fix: correct rust toolchain version in release.yml

---

xline/src/id_gen.rs
xline/src/server/lease_server.rs
xline/src/server/lock_server.rs
xline/src/server/xline_server.rs

fix bug in lock test
generate unique lease id instead use timestamp
no

fix bug in lock test

---

engine/src/engine_api.rs
engine/src/memory_engine.rs
engine/src/rocksdb_engine.rs
xline/src/server/command.rs
xline/src/storage/auth_store/backend.rs
xline/src/storage/auth_store/store.rs
xline/src/storage/db.rs
xline/src/storage/kv_store.rs
xline/src/storage/lease_store/mod.rs
xline/src/storage/storage_api.rs

refactor write operation, use reference in delete operations

---

curp/src/rpc/mod.rs
curp/src/server/curp_node.rs
curp/src/server/raw_curp/mod.rs
curp/src/server/raw_curp/state.rs
curp/src/server/raw_curp/tests.rs

If ae failed, will now fallback to calibrate instead of retrying.
Also, we have only one hb_opt flag. This is not enough because failed server also needs hb. So we need hb flag for each server.

Normal AE will not retry.

---

engine/src/memory_engine.rs
engine/src/rocksdb_engine.rs

Add test coverage for `write_all` and `read_exact` in snapshot

test: add test coverage for write_all and read_exact

---

xline/Cargo.toml
xline/src/client/mod.rs
xline/src/server/command.rs
xline/src/server/kv_server.rs
xline/src/server/lock_server.rs
xline/src/server/watch_server.rs
xline/src/storage/auth_store/perms.rs
xline/src/storage/auth_store/store.rs
xline/src/storage/index.rs
xline/src/storage/kv_store.rs

refactor PermissionCache and KeyRange

---

curp/src/server/curp_node.rs
curp/src/server/gc.rs
curp/tests/common/curp_group.rs
utils/Cargo.toml
utils/src/config.rs
xline/src/main.rs
xline_server.conf

read gc interval from config file

---

QUICK_START.md
curp/src/server/curp_node.rs
curp/src/server/raw_curp/log.rs
curp/src/server/raw_curp/mod.rs
curp/src/server/raw_curp/tests.rs
scripts/benchmark.sh
scripts/quick_start.sh
utils/src/config.rs
utils/src/lib.rs
xline/src/main.rs

Improving Xline throughput by batching in the high-load scenario. This pr is based on #224 . Close #220 
Improving Xline throughput by batching in the high-load scenario.
No

New batching

---

curp/src/cmd.rs
curp/src/rpc/connect.rs
curp/src/server/cmd_worker/conflict_checked_mpmc.rs
curp/src/server/curp_node.rs
curp/src/server/storage/mod.rs
curp/src/server/storage/rocksdb.rs
curp/src/snapshot.rs
curp/src/test_utils/test_cmd.rs
curp/tests/common/test_cmd.rs
engine/src/engine_api.rs
engine/src/lib.rs
engine/src/memory_engine.rs
engine/src/rocksdb_engine.rs
engine/src/snapshot_api/memory_snapshot.rs
engine/src/snapshot_api/mod.rs
engine/src/snapshot_api/rocks_snapshot.rs
xline/src/client/restore.rs
xline/src/server/command.rs
xline/src/server/maintenance.rs
xline/src/storage/db.rs
xline/src/storage/storage_api.rs

add real implementation of snapshot and reset in the command executor.
refactor snapshot at engine level
no

refactor snapshot at engine level, and fix todo in `CommandExecutor`

---

xline/tests/maintenance.rs

Fix #240 
the maintenance_client sends a request directly to the leader, because other nodes may not have synced yet
no

fix snapshot restore test

---

xline/src/server/lock_server.rs
xline/src/server/maintenance.rs

Generate a stream in a more human-readable way.
Reading #248 for more details.
No

refactor: use async::stream macro to generate stream

---

MAINTAINERS

doc: update MAINTAINERS file

---

.github/ISSUE_TEMPLATE/bug_report.yaml
README.md

doc: add curp blog for cncf sandbox review

---

.pre-commit-config.yaml
QUICK_START.md
README.md
VALIDATION_REPORT.md

Update some docs.  Closes: #271, #272, #273

doc: update documents

---

engine/src/rocksdb_engine.rs

Clean up test temp files
Remove directory after test
No

Clean up test temp files

---

xline/src/server/barriers.rs

Close #291
fix #291
Only update `last_trigger_index` with a larger index when triggered
no

fix(IndexBarrier): fix trigger of `IndexBarrier`

---

xline/src/main.rs
xline/src/server/command.rs
xlineapi/src/lib.rs

fix: fix conflict between lease request and kv request

---

Cargo.toml
xline-client/Cargo.toml
xline-client/README.md
xline-client/src/clients/auth.rs
xline-client/src/clients/cluster.rs
xline-client/src/clients/election.rs
xline-client/src/clients/kv.rs
xline-client/src/clients/lease.rs
xline-client/src/clients/lock.rs
xline-client/src/clients/maintenance.rs
xline-client/src/clients/mod.rs
xline-client/src/clients/watch.rs
xline-client/src/error.rs
xline-client/src/lib.rs
xlineapi/src/lib.rs

Add a new Xline client crate, offering an external client for Xline.
`xline-client` crate. The clients are currently placeholders, they will get implemented in other PRs.
No

Feature/Xline Client

---

Cargo.lock
curp/src/client.rs
curp/src/server/raw_curp/mod.rs
curp/src/server/raw_curp/tests.rs
xline/src/server/kv_server.rs
xline/src/storage/kv_store.rs

Revert two commits

---

.pre-commit-config.yaml

1. forbidden to commit directly to the main or master branch
2. run unit tests before every commit 

Update pre commit config

---

xline/src/main.rs

Feature/Support dns resolution for Xline cluster

---

xline/Cargo.toml

update xline binary version

---

curp/src/server/raw_curp/log.rs

refactor: merge entries and batch_index in raw_curp

---

README.md

Add OpenSSF Best Practices Badge in the README doc to meet the requirement from cncf toc.  FYI: https://github.com/cncf/toc/issues/1093

docs: add OpenSSF Best Practices Badge in README doc

---

curp-test-utils/src/lib.rs
curp-test-utils/src/test_cmd.rs
curp/src/server/curp_node.rs
curp/src/server/storage/db.rs
curp/src/server/storage/mod.rs
curp/tests/common/curp_group.rs
simulation/src/curp_group.rs
utils/src/config.rs
xline-test-utils/src/lib.rs
xline/src/main.rs

make curp storage engine configurable.

refactor: refactor curp_server storage implementation

---

Cargo.lock
xline/Cargo.toml
xline/src/server/xline_server.rs

Add [gRPC Health Checking Protocol](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) to xline.
Start gRPC Health Server when starting xline.
No

feat: support grpc health checking protocol

---

xline-client/src/clients/kv.rs
xline-client/tests/kv.rs
xline-client/tests/watch.rs

refactor: remove unnecessary mutable borrow in `xline-client`

---

Cargo.lock
Cargo.toml
curp-test-utils/Cargo.toml
curp/Cargo.toml
curp/src/rpc/mod.rs
engine/Cargo.toml
simulation/Cargo.toml
utils/Cargo.toml
xline-client/Cargo.toml
xline-test-utils/Cargo.toml
xline/Cargo.toml
xlineapi/Cargo.toml
xlineapi/src/lib.rs

This new version include a fix to the issue https://github.com/madsim-rs/madsim/issues/155, which may cause client hanging in current CI

chore: bump madsim-tonic version to v0.3.0(tonic v0.9.2)

---

xline-client/README.md
xline-client/src/clients/cluster.rs
xline-client/src/clients/election.rs
xline-client/src/clients/maintenance.rs
xline-client/src/clients/mod.rs
xline-client/src/clients/watch.rs
xline-client/src/error.rs
xline-client/src/lib.rs
xline-client/src/types/auth.rs
xline-client/src/types/kv.rs
xline-client/src/types/watch.rs
xline-client/tests/common.rs
xline-client/tests/maintenance.rs

descibed in `Update README` section in #369
This RP add readme to `xline-client`, and some refactors related to the readme.
Note that some RPs of `xline-client` still not merged. The readme part need to update with these APIs being implemented.

doc: update xline client readme

---

xlinectl/README.md

docs: xlinectl document

---

CHANGELOG.md
README.md

chore(release): update CHANGELOG.md and README.md for v0.5.0

---

curp/doc/key_based_channel_optimization.md
xline/src/server/kv_server.rs
xline/src/storage/kv_store.rs
xline/src/storage/kvwatcher.rs
xline/src/storage/lease_store/mod.rs
xline/tests/auth_test.rs
xline/tests/kv_test.rs
xline/tests/lease_test.rs
xline/tests/lock_test.rs
xline/tests/watch_test.rs
xlineapi/src/lib.rs

Reopen #367 
(Accidentally closed)

refactor: read only txn request will use read state mechanism

---

.github/workflows/docker.yml
.github/workflows/merge_image.yml
.github/workflows/release.yml

Test workflow: https://github.com/iGxnon/Xline/actions/runs/5830042498
Replace dockerhub to GitHub container registry  
See above
No

CI/Replace Dockerhub to GitHub Container Registry

---

scripts/validation_test.sh
xline/src/request_validation.rs
xline/src/server/auth_server.rs
xline/src/server/kv_server.rs
xline/src/server/lease_server.rs
xline/src/server/lock_server.rs
xline/src/storage/execute_error.rs

refactor: etcd rpc error compat

---

curp/src/server/raw_curp/mod.rs

The recovery process for uncommitted pool is wrong and unnecessary
remove recovery of uncommitted pool
no

fix: remove recovery of uncommitted pool

---

.github/workflows/benchmark.yml
.github/workflows/validation.yml
curp/src/members.rs
curp/src/rpc/mod.rs
curp/src/server/cmd_worker/mod.rs
doc/quick-start/README.md
scripts/benchmark.sh
scripts/quick_start.sh
simulation/src/curp_group.rs
xline/src/storage/execute_error.rs
xlineapi/src/lib.rs

docs: modify the docker pulling command in quick-start.md

---

xline-client/src/types/auth.rs
xlinectl/README.md
xlinectl/src/command/mod.rs
xlinectl/src/command/user/add.rs
xlinectl/src/command/user/delete.rs
xlinectl/src/command/user/get.rs
xlinectl/src/command/user/grant_role.rs
xlinectl/src/command/user/list.rs
xlinectl/src/command/user/mod.rs
xlinectl/src/command/user/passwd.rs
xlinectl/src/command/user/revoke_role.rs
xlinectl/src/main.rs
xlinectl/src/utils/printer.rs

feat: implement xlinectl `user` commands

---

curp/build.rs
curp/src/client.rs
curp/src/lib.rs
curp/src/members.rs
curp/src/rpc/connect.rs
curp/src/rpc/mod.rs
curp/src/server/curp_node.rs
curp/src/server/mod.rs
curp/tests/common/curp_group.rs
simulation/src/curp_group.rs

chore: merge fetch leader into fetch cluster

---

Cargo.lock
xline-client/src/types/auth.rs
xlinectl/Cargo.toml
xlinectl/README.md
xlinectl/src/command/mod.rs
xlinectl/src/command/role/add.rs
xlinectl/src/command/role/delete.rs
xlinectl/src/command/role/get.rs
xlinectl/src/command/role/grant_perm.rs
xlinectl/src/command/role/list.rs
xlinectl/src/command/role/mod.rs
xlinectl/src/command/role/revoke_perm.rs
xlinectl/src/main.rs
xlinectl/src/utils/printer.rs

feat: implement xlinectl `role` commands

---

curp/proto/inner_message.proto
curp/src/rpc/mod.rs
curp/src/server/curp_node.rs
curp/src/server/raw_curp/mod.rs
curp/src/server/raw_curp/tests.rs
simulation/tests/it/curp/server_election.rs

Support pre vote phase
Avoid timed out nodes from disrupting a healthy cluster
Add pre vote and add more check when node receive a vote request
no

[Feature]: Support pre vote phase

---

curp/src/server/cmd_worker/conflict_checked_mpmc.rs
simulation/tests/it/curp/server_election.rs

fix reelect test
modify assert in this test
no

chore: fix reelect test

---

xline-client/src/clients/watch.rs
xline-client/src/types/watch.rs
xline-client/tests/watch.rs

fix: fix `Watcher`

---

curp-test-utils/src/test_cmd.rs
curp/proto/inner_message.proto
curp/src/log_entry.rs
curp/src/members.rs
curp/src/rpc/mod.rs
curp/src/server/cmd_worker/conflict_checked_mpmc.rs
curp/src/server/cmd_worker/mod.rs
curp/src/server/curp_node.rs
curp/src/server/raw_curp/mod.rs
curp/src/server/raw_curp/state.rs
curp/src/server/raw_curp/tests.rs
curp/tests/common/curp_group.rs
curp/tests/server.rs
simulation/tests/it/curp/server_recovery.rs
utils/src/shutdown.rs

Stop removed node and start added node 

---

scripts/validation_test.sh

add member tests to validation test
add member tests to validation test
no

test: add member tests to validation test

---

curp/src/members.rs
utils/src/config.rs
utils/src/lib.rs
xline/src/main.rs
xline/src/server/xline_server.rs

update start logic in xline binary
update start logic in xline binary
no

feat: update start logic in xline binary

---

curp/tests/common/curp_group.rs
curp/tests/server.rs

update submodule's version
update submodule's version
no

chore: update submodule's version

---

Cargo.lock
curp-external-api/src/cmd.rs
curp-test-utils/src/lib.rs
curp-test-utils/src/test_cmd.rs
curp/src/server/cmd_worker/conflict_checked_mpmc.rs
curp/src/server/cmd_worker/mod.rs
curp/src/server/raw_curp/state.rs
curp/tests/server.rs
utils/src/lib.rs
xline-test-utils/src/lib.rs
xline/Cargo.toml
xline/src/server/cluster_server.rs
xline/src/server/command.rs
xline/src/storage/auth_store/perms.rs
xline/tests/auth_test.rs
xline/tests/cluster_test.rs
xline/tests/kv_test.rs
xline/tests/lease_test.rs
xline/tests/maintenance.rs

Add tests for xline cluster server
Add tests for xline cluster server
no

Xline cluster test

---

.github/workflows/docker.yml
.github/workflows/release.yml

ci: checkout submodule in release ci processs

---

.github/workflows/ci.yml

ci: pin cargo outdated's version to v0.13.1

---

CONTRIBUTING.md
README.md

docs: update README and CONTRIBUTING doc

---

README.md

doc: fix typo and unified etcd writing

---

curp/proto/inner_message.proto
curp/src/rpc/connect.rs
curp/src/rpc/mod.rs
curp/src/server/cmd_worker/mod.rs
curp/src/server/curp_node.rs
curp/src/server/mod.rs
curp/src/server/raw_curp/mod.rs
curp/src/server/raw_curp/state.rs
curp/src/server/raw_curp/tests.rs
utils/src/shutdown.rs

#526 
fix cluster shutdown after member add
Add a new phase for shutdown
no

fix: fix cluster shutdown after member add

---

doc/quick-start/Dockerfile
scripts/Dockerfile
scripts/quick_start.sh
scripts/start_xline.sh

Add a startup_xline.sh script to boot up xline service in docker. Therefore, we can generate the k8s pod template more smoothly.

build: modify the dockerfile and bootup logic

---

Cargo.lock
curp/Cargo.toml
curp/src/server/storage/mod.rs
curp/src/server/storage/wal/error.rs
curp/src/server/storage/wal/mod.rs
curp/src/server/storage/wal/util.rs

There will be 6 PRs of the CURP WAL implementation, this is the 1st part.
This PR implements some file utils and error types in CURP WAL.
No

feat: CURP WAL utils

---

curp/src/log_entry.rs
curp/src/rpc/mod.rs
curp/src/server/storage/wal/codec.rs
curp/src/server/storage/wal/mod.rs

Based on: #562
There will be 6 PRs of the CURP WAL implementation, this is the 2nd part.
This PR implements the WAL codec

feat: CURP WAL codec

---

scripts/quick_start.sh
scripts/start_xline.sh

chore: boot up xline server from env

---

curp/src/server/cmd_worker/conflict_checked_mpmc.rs
curp/src/server/cmd_worker/mod.rs
utils/src/shutdown.rs

fix ce event tx logs
fix ce event tx logs
no

fix: fix ce event tx logs

---

Cargo.lock
simulation/Cargo.toml
simulation/src/xline_group.rs
simulation/tests/it/xline.rs
utils/src/config.rs
xline-client/src/clients/kv.rs
xline-client/src/lib.rs
xline/Cargo.toml
xline/src/main.rs
xline/src/server/command.rs
xline/src/server/kv_server.rs
xline/src/server/xline_server.rs
xline/src/storage/kv_store.rs
xlineapi/src/command.rs
xlineapi/src/lib.rs

fix validation blocking
fix compact physical logic
no

fix: fix compact physical logic

---

Cargo.lock
xline/Cargo.toml
xline/src/server/maintenance.rs
xline/src/server/xline_server.rs
xline/src/storage/db.rs
xline/src/storage/index.rs
xline/src/storage/kv_store.rs
xline/src/storage/storage_api.rs

support hash and hash_kv rpc in maintenance server
add hash and hash_kv implementation
no

feat: support hash and hash_kv

---

.github/workflows/pull_request.yml
.github/workflows/validation.yml

Running pull_request ci check on every branch.

ci: running pull_request check on every branch

---

curp/src/members.rs
curp/src/server/cmd_worker/mod.rs
curp/src/server/curp_node.rs
curp/src/server/mod.rs
curp/src/server/raw_curp/mod.rs
curp/src/server/raw_curp/tests.rs
xline-client/src/clients/maintenance.rs
xline/src/server/maintenance.rs
xline/src/server/xline_server.rs
xline/src/storage/alarm_store.rs
xline/tests/it/maintenance_test.rs
xlineapi/src/lib.rs

Based on #548 
Support get more field in status 
Support get more field in status 
no

[Feature]: Support get more field in status 

---

scripts/validation_test.sh

fix validation test and add more logs
fix validation test and add more logs
no

[Test]: fix validation test and add more logs

---

curp/proto/inner_message.proto
curp/src/client/mod.rs
curp/src/client/retry.rs
curp/src/client/unary.rs
curp/src/members.rs
curp/src/rpc/connect.rs
curp/src/rpc/mod.rs
curp/src/server/curp_node.rs
curp/src/server/mod.rs
curp/src/server/raw_curp/mod.rs
curp/src/server/raw_curp/state.rs
curp/src/server/raw_curp/tests.rs
curp/tests/it/server.rs
xline/src/server/maintenance.rs

Support move leader
Support move leader
no

[Feature]: support move leader

---

.config/nextest.toml

Add `nextest.toml` configuration.

ci: add nextest config

---

.github/workflows/pull_request.yml
Cargo.lock
Cargo.toml
benchmark/Cargo.toml
ci/Dockerfile
ci/scripts/check-trailing-spaces.sh
ci/scripts/upload-codecov.sh
curp-external-api/Cargo.toml
curp-test-utils/Cargo.toml
curp/Cargo.toml
simulation/Cargo.toml
utils/Cargo.toml
workspace-hack/Cargo.toml
xline-client/Cargo.toml
xline/Cargo.toml
xline/src/storage/alarm_store.rs
xline/src/storage/auth_store/perms.rs
xlineapi/Cargo.toml
xlineapi/src/lib.rs
xlinectl/Cargo.toml

fix ci codecov upload script & check tailing space script
fix ci codecov upload script & check tailing space script
no

ci: fix ci scripts

---

curp/src/server/mod.rs
curp/tests/it/common/curp_group.rs
utils/src/config.rs
xline-test-utils/src/bin/test_cluster.rs
xline-test-utils/src/lib.rs
xline/src/main.rs
xline/tests/it/cluster_test.rs
xline/tests/it/maintenance_test.rs

support start `CurpGroup` and `Cluster` with external configuration
Refactor test framework
no

[Refactor]: test framework

---

xline/tests/it/maintenance_test.rs

#623 
fix test_status
fix test_status
no

[fix]: fix test_status

---

xline-client/README.md

add dependency on protobuf-compiler in xline-client/README.md

docs: add dependency on protobuf-compiler in xline-client/README.md

---

Cargo.lock
benchmark/Cargo.toml
workspace-hack/Cargo.toml
xline/Cargo.toml
xlinectl/Cargo.toml

upgrade the dependent version to fix audit
upgrade the dependent version to fix audit
no

fix: upgrade the dependent version to fix audit

---

curp-external-api/src/role_change.rs
curp-test-utils/src/lib.rs
curp/src/server/curp_node.rs
curp/src/server/raw_curp/mod.rs
curp/src/server/raw_curp/state.rs
curp/src/server/raw_curp/tests.rs
xline/src/state.rs
xline/tests/it/maintenance_test.rs

create RawCurp and Context by builder pattern

[Refactor]: create RawCurp and Context by builder pattern

---

.github/workflows/pull_request.yml
ci/scripts/upload-codecov.sh

Attempt to restore the code cov format to the past, fixing the issue of cov not being updated.
Update `pull_request.yml`
No

ci: update code cov format

---

.github/ISSUE_TEMPLATE/bug_report.yaml
Cargo.lock
xline/Cargo.toml

chore: update xline version in Cargo.toml

---

README.md

docs: update README doc

---

.github/workflows/pull_request.yml

chore: filter push in pull request ci

---

benchmark/src/bench_client.rs
curp/src/client/retry.rs
curp/src/client/unary.rs
curp/src/lib.rs
curp/src/log_entry.rs
curp/src/server/raw_curp/mod.rs
curp/src/server/raw_curp/state.rs
curp/src/server/raw_curp/tests.rs
curp/src/server/spec_pool.rs
curp/src/server/storage/db.rs
curp/src/server/storage/wal/codec.rs
utils/src/config.rs
xline-client/src/clients/kv.rs
xline-client/tests/it/auth.rs
xline-client/tests/it/kv.rs
xline-client/tests/it/lease.rs
xline-client/tests/it/lock.rs
xline-client/tests/it/maintenance.rs
xline/src/server/maintenance.rs
xline/src/storage/db.rs
xlineapi/src/command.rs
xlineapi/src/execute_error.rs

fix: fix the calculation logic of superquorum

---

Cargo.lock
curp-test-utils/src/lib.rs
curp/Cargo.toml
curp/src/rpc/connect.rs
curp/src/rpc/mod.rs
curp/src/server/curp_node.rs
curp/src/server/lease_manager.rs
curp/src/server/mod.rs
curp/src/server/raw_curp/mod.rs
curp/src/server/raw_curp/tests.rs

Signed-off-by: iGxnon <igxnon@gmail.com>
Add client id lease mechanism, this is the part 1 PR.
Implement lease server & lease keep alive connection.
No.

Feat/dedup-lease (part 1)

---

README.md

chore: update xlinectl link and Xline client sdk link

---

crates/curp/src/server/raw_curp/mod.rs

test: fix concurrent_cmd_order_should_have_correct_revision blocking

---

Cargo.lock
Cargo.toml
crates/engine/Cargo.toml
crates/engine/src/metrics.rs
crates/engine/src/mock_rocksdb_engine.rs
crates/engine/src/proxy.rs
crates/engine/src/rocksdb_engine.rs
crates/engine/src/snapshot_allocator.rs
crates/utils/src/table_names.rs
crates/xline/src/restore.rs
crates/xline/src/server/command.rs
crates/xline/src/storage/alarm_store.rs
crates/xline/src/storage/auth_store/backend.rs
crates/xline/src/storage/auth_store/mod.rs
crates/xline/src/storage/db.rs
crates/xline/src/storage/kv_store.rs
crates/xline/src/storage/lease_store/mod.rs
crates/xlinectl/Cargo.toml
crates/xlineutl/Cargo.toml
crates/xlineutl/README.md
crates/xlineutl/src/command/mod.rs
crates/xlineutl/src/command/snapshot.rs
crates/xlineutl/src/main.rs
workspace-hack/Cargo.toml

support restore snapshot
support restore snapshot
no

feature: support restore snapshot

---

crates/xline/src/storage/compact/mod.rs
crates/xline/src/storage/db.rs
crates/xline/src/storage/kv_store.rs

add scheduled compact revision persistent
add scheduled compact revision persistent
no

feat: add scheduled compact revision persistent

---

crates/curp/src/lib.rs
crates/curp/src/tracker.rs

Add tracker.
Add `tracker.rs`.
No

feat: implement tracker

---

crates/curp/src/error.rs
crates/curp/src/log_entry.rs
crates/curp/src/members.rs
crates/curp/src/server/curp_node.rs
crates/curp/src/server/mod.rs
crates/curp/src/server/raw_curp/mod.rs
crates/curp/src/server/raw_curp/tests.rs
crates/curp/src/server/storage/db.rs
crates/curp/src/server/storage/mod.rs
crates/curp/tests/it/common/curp_group.rs
crates/simulation/src/curp_group.rs
crates/simulation/src/xline_group.rs
crates/simulation/tests/it/xline.rs
crates/xline/src/server/xline_server.rs

Persist the member and restore cluster info from the store
Persist the member and restore cluster info from the store
no

[feature]: member persistent

---

Cargo.lock
crates/xline/src/storage/mod.rs
crates/xline/src/storage/revision.rs
crates/xlineutl/Cargo.toml
crates/xlineutl/src/command/snapshot.rs
crates/xlineutl/src/main.rs
crates/xlineutl/src/printer.rs

based on #615 
support xlineutl snapshot status
support xlineutl snapshot status
no

[Feat]: xlineutl snapshot status

---

crates/curp/src/server/storage/wal/mod.rs
crates/curp/src/server/storage/wal/pipeline.rs

Based on : #563
Implement CURP WAL
This PR implements the WAL pipeline part, the file pipeline is used for pre-allocating files for WAL segment.

feat: CURP WAL Pipeline

---

crates/curp/src/server/storage/wal/mod.rs
crates/curp/src/server/storage/wal/segment.rs

based on: #571
Implement CURP WAL
This PR implements the WAL segment part.

feat: CURP WAL Segment

---

.github/workflows/pull_request.yml
ci/artifacts/kind-node-xline.Dockerfile
ci/artifacts/kind.yaml
ci/artifacts/xline-pod.yaml
ci/scripts/kind.sh

Add github action to run e2e test with kubernetes cluster.

Add github action to run e2e test with kubernetes cluster.

---

.github/workflows/issue-cmds.yml
.github/workflows/issue-welcome.yml

add an issue bot so that contributors can assign the issue to themselves.

chore: add an issue bot

---

.github/workflows/pull_request.yml

ci: fix crate-ci/typos version to v1.19.0

---

.github/workflows/issue-cmds.yml
.github/workflows/issue-welcome.yml

fix: switch help command permission level to read

---

.github/workflows/pull_request.yml
.mergify.yml

mergify best practice

---

crates/engine/src/api/engine_api.rs
crates/engine/src/api/operation.rs
crates/engine/src/memory_engine/mod.rs
crates/engine/src/memory_engine/transaction.rs
crates/engine/src/metrics.rs
crates/engine/src/mock_rocksdb_engine.rs
crates/engine/src/proxy.rs
crates/engine/src/rocksdb_engine/mod.rs
crates/engine/src/rocksdb_engine/transaction.rs

Depends-On: #674 
Implement txn API for rocksdb engine.

feat: implement rocks transaction

---

crates/curp-test-utils/src/test_cmd.rs
crates/curp/src/server/storage/db.rs
crates/engine/src/api/engine_api.rs
crates/engine/src/api/operation.rs
crates/engine/src/memory_engine/mod.rs
crates/engine/src/metrics.rs
crates/engine/src/mock_rocksdb_engine.rs
crates/engine/src/proxy.rs
crates/engine/src/rocksdb_engine/mod.rs
crates/engine/src/rocksdb_engine/transaction.rs
crates/simulation/tests/it/curp/server_recovery.rs
crates/xline/src/storage/db.rs

Depends-On: #703 
Implements `StorageOps` for Engine

refactor: engine refactor

---

crates/xlinectl/src/command/watch.rs
scripts/validation_test.sh

To solve issue: #824 
A : change the `xlinectl watch` command.

feat: add exec command support for xlinectl watch

---

.mergify.yml

Allows reviewing PRs that have failed CI checks on other branches.

chore(mergify): convert to draft only on master branch

---

crates/xline-client/README.md
crates/xline-client/src/clients/auth.rs
crates/xline-client/src/clients/kv.rs
crates/xline-client/src/clients/lock.rs
crates/xline-client/src/clients/watch.rs

- fix doc test failed introduced by #882
- fix doc test

fix(client): doc-test failed introduced by #882

---

crates/curp-external-api/src/conflict.rs
crates/curp/src/log_entry.rs
crates/curp/src/server/cmd_worker/mod.rs
crates/curp/src/server/conflict/mod.rs
crates/curp/src/server/conflict/spec_pool_new.rs
crates/curp/src/server/conflict/test_pools.rs
crates/curp/src/server/conflict/tests.rs
crates/curp/src/server/conflict/uncommitted_pool.rs
crates/xline/src/conflict/mod.rs
crates/xline/src/conflict/spec_pool.rs
crates/xline/src/conflict/tests.rs
crates/xline/src/conflict/uncommitted_pool.rs
crates/xline/src/server/lease_server.rs
crates/xline/src/server/xline_server.rs
crates/xline/src/storage/lease_store/lease.rs
crates/xline/src/storage/lease_store/lease_collection.rs
crates/xline/src/storage/lease_store/lease_queue.rs
crates/xline/src/storage/lease_store/mod.rs
crates/xlineapi/src/command.rs
crates/xlineapi/src/lib.rs

Depends-On: #852 
Fix lease related logic in conflict pools.

fix: lease keys in conflict pool

---

crates/xline-client/examples/auth_user.rs
crates/xline-client/src/clients/auth.rs
crates/xline-client/src/types/auth.rs
crates/xline-client/tests/it/auth.rs
crates/xline-test-utils/src/lib.rs
crates/xlinectl/src/command/user/grant_role.rs

- one of the series change of #819
- yes

refactor(client)!: Remove request wrappers - AuthClient::user_grant_role

---

crates/xline-client/examples/auth_user.rs
crates/xline-client/src/clients/auth.rs
crates/xline-client/src/types/auth.rs
crates/xline-client/tests/it/auth.rs
crates/xlinectl/src/command/user/revoke_role.rs

refactor(client)!: Remove request wrappers - AuthClient::user_revoke_role

---

crates/xline-client/examples/auth_role.rs
crates/xline-client/src/clients/auth.rs
crates/xline-client/src/types/auth.rs
crates/xline-client/tests/it/auth.rs
crates/xline-test-utils/src/lib.rs
crates/xlinectl/src/command/role/add.rs

refactor(client)!: Remove request wrappers - AuthClient::role_add

---

crates/xline-client/examples/auth_role.rs
crates/xline-client/src/clients/auth.rs
crates/xline-client/src/types/auth.rs
crates/xline-client/tests/it/auth.rs
crates/xline/tests/it/auth_test.rs
crates/xlinectl/src/command/role/delete.rs

refactor(client)!: Remove request wrappers - AuthClient::role_delete

---

crates/benchmark/src/bench_client.rs
crates/simulation/src/xline_group.rs
crates/xline-client/README.md
crates/xline-client/examples/kv.rs
crates/xline-client/src/clients/kv.rs
crates/xline-client/src/types/kv.rs
crates/xline-client/tests/it/kv.rs
crates/xline/tests/it/auth_test.rs
crates/xline/tests/it/kv_test.rs
crates/xline/tests/it/lease_test.rs
crates/xline/tests/it/maintenance_test.rs
crates/xlinectl/src/command/get.rs
crates/xlinectl/src/command/txn.rs

refactor(client)!: Remove request wrappers - KvClient::range

---

crates/xline-client/examples/kv.rs
crates/xline-client/src/clients/kv.rs
crates/xline-client/src/types/kv.rs
crates/xline-client/tests/it/kv.rs
crates/xline/tests/it/kv_test.rs
crates/xline/tests/it/watch_test.rs
crates/xlinectl/src/command/delete.rs
crates/xlinectl/src/command/txn.rs

refactor(client)!: Remove request wrappers - KvClient::delete

---

crates/curp/src/client/unary.rs
crates/curp/src/server/cmd_worker/mod.rs
crates/curp/src/server/conflict/spec_pool_new.rs
crates/curp/src/server/raw_curp/mod.rs
crates/curp/src/server/raw_curp/tests.rs
crates/utils/src/config.rs
crates/xline/src/server/command.rs

This PR includes several fixes:
- node not being published in member add
- switch config on both leader and follower
- prevent panic when applying a conf change entry on a restarted follower

fix: membership change

---

crates/curp/src/client/mod.rs

refactor: set retry count to a higher value to avoid test failures

---

crates/curp/src/server/conflict/spec_pool_new.rs
crates/curp/src/server/curp_node.rs
crates/utils/src/task_manager/mod.rs
crates/utils/src/task_manager/tasks.rs

This PR reafctor the task manager, allowing directly abort cancel safe tasks.

refactor: task manager

---

crates/curp/src/client/mod.rs

This PR add a retry loop to prevent receiving empty address from `FetchCluster` (some nodes haven't been published yet).

refactor: add retry for client initial cluster node discovery

---

.github/ISSUE_TEMPLATE/bug_report.yaml

chore: update bug_report.yaml

---

Cargo.lock
crates/utils/src/tracing.rs
workspace-hack/Cargo.toml

chore: update cargo dependencies
